### ISSUE TITLE
custom actionbar layout causes out of memory error

### ISSUE THREAD

**Issue by Tamas-** [JakeWharton/ActionBarSherlock#1024]
I wanted to use custom colors in my actionbar, so I used a custom layout which worked great for me, on a lot of devices(htc one, nexus4, sgs4, sgs2, galaxy chat, etc).

```
getSupportActionBar().setCustomView(R.layout.actionbar_layout);
getSupportActionBar().setDisplayShowCustomEnabled(true);
```

This my actionbar_layout.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"  the height does not matter, tried it with wrap_content or a fixed height also
    android:orientation="vertical" >

    <TextView
        android:id="@+id/actionbar_title"
        android:layout_width="fill_parent"
        android:layout_height="@dimen/dialog_button_height" //this also does not seem to matter
        android:ellipsize="end"
        android:gravity="center"
        android:maxHeight="1dp"
        android:maxLines="1"
        android:scrollHorizontally="true"
        android:text="Bacon ipsum dolor sit amet frankfurter flank chicken, pig short loin ham hock short ribs hamburger. Capicola ham hock meatball chicken andouille swine shankle fatback turducken, tail corned beef jowl leberkas. Ground round andouille tri-tip tail, shank meatball jerky strip steak bresaola. Rump chuck ball tip, pork capicola venison pancetta swine jowl leberkas sausage turducken beef. Fatback frankfurter doner, bresaola shoulder sausage meatloaf tongue short ribs sirloin. Capicola ground round shankle, jowl pork loin tongue sirloin pork belly. Drumstick meatloaf prosciutto flank bresaola pork loin doner."
        android:textColor="#777777"
        android:textSize="20sp" />

</LinearLayout>
```

This happened on my galaxy ace on the start of my app (android 2.3.6):

```
08-27 10:05:54.867: E/AndroidRuntime(7276): FATAL EXCEPTION: main
08-27 10:05:54.867: E/AndroidRuntime(7276): java.lang.IllegalArgumentException: bitmap size exceeds 32bits
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.graphics.Bitmap.nativeCreate(Native Method)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.graphics.Bitmap.createBitmap(Bitmap.java:477)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.View.buildDrawingCache(View.java:6577)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.ViewGroup.onAnimationStart(ViewGroup.java:1259)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.ViewGroup.drawChild(ViewGroup.java:1505)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.View.draw(View.java:6883)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.widget.FrameLayout.draw(FrameLayout.java:357)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.View.draw(View.java:6883)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.View.draw(View.java:6883)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.widget.FrameLayout.draw(FrameLayout.java:357)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1940)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.ViewRoot.draw(ViewRoot.java:1527)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.ViewRoot.performTraversals(ViewRoot.java:1264)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.view.ViewRoot.handleMessage(ViewRoot.java:1865)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.os.Handler.dispatchMessage(Handler.java:99)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.os.Looper.loop(Looper.java:130)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at android.app.ActivityThread.main(ActivityThread.java:3687)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at java.lang.reflect.Method.invokeNative(Native Method)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at java.lang.reflect.Method.invoke(Method.java:507)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
08-27 10:05:54.867: E/AndroidRuntime(7276):     at dalvik.system.NativeStart.main(Native Method)
```

So the app will crash if I include the custom actionbar layout. 
I also have a ton of big images in my app, and also in the manifest I have:

```
   android:largeHeap="true"
```

I'm also using gradients, so I also have:

```
getWindow().setFormat(PixelFormat.RGBA_8888);
```

My current fix for this:

Luckily, I only want a custom color, so I can do instead of the custom layout this (from stackowerflow: http://stackoverflow.com/questions/10352022/how-to-set-title-color-in-actionbarsherlock):

```
getSupportActionBar().setTitle(Html.fromHtml("<font color='#ffffff'>App Name</font>"));
```

**Comment by JakeWharton** [comment]
That exception indicates a problem with your Bitmap, not an out of memory error. And that stack trace doesn't even run through ActionBarSherlock.

**Comment by Tamas-** [comment]
I don't have a bitmap in the custom layout, it's just a linearlayout(without a background image) and a textview. 
If I recreate them programmatically, it also works. But if I set the custom layout as an xml file, it will crash.

Also, if you include the above layout in a hello world app, it will also crash.

here is a hello world sample project: pastelink.me/dl/853c78#sthash.GsVTyWmb.dpuf
please note, that it only crashes for me on the galaxy ace (2.3.6)
