### ISSUE TITLE
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by Im0rtality** [JakeWharton/ActionBarSherlock#1031]
I'm receiving following exception in crash reports from app (20-ish in 3 days, ~100 users).

Checked project according to [this (FragmentTransactions & Activity State Loss)](http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html) article and found no calls to commit altogether. Checked for any select\* calls as well and found nothing relevant.

Using 4.3.1 version

Stack trace (logcat has nothing relevant)

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1327)
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1338)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:574)
    at com.actionbarsherlock.internal.app.ActionBarImpl.selectTab(ActionBarImpl.java:536)
    at com.actionbarsherlock.internal.app.ActionBarImpl$TabImpl.select(ActionBarImpl.java:912)
    at com.actionbarsherlock.internal.widget.ScrollingTabContainerView$TabClickListener.onClick(ScrollingTabContainerView.java:504)
    at android.view.View.performClick(View.java:2485)
    at android.view.View$PerformClick.run(View.java:9080)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3683)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by iNoles** [comment]
By looking to the stack trace, it looks like you are trying to select a new Tab under View click?

**Comment by Im0rtality** [comment]
Nope, application does not have such functionality.

**Comment by rishabhmhjn** [comment]
Did you try `fragmentTransaction.commitAllowingStateLoss();` ?

**Comment by Im0rtality** [comment]
@rishabhmhjn, as wrote in initial message, not using FragmentTransaction.commit() anywhere in code

**Comment by rishabhmhjn** [comment]
@Im0rtality Dont remember correctly but I also faced the same problem long time ago.
Try my solution mentioned here - http://stackoverflow.com/a/16995117/842214

**Comment by Im0rtality** [comment]
@rishabhmhjn I have wrapped up plausible locations with `isFinishing()` and log sending if is actually finishing. Gonna post results after deployment.

**Comment by Im0rtality** [comment]
Thanks, that `isFinishing()` solved it.

**Comment by swatigoel** [comment]
@Im0rtality can you please tell me where to use isFinishing() to avoid this problem.

**Comment by rasik1010** [comment]
@Im0rtality , @rishabhmhjn  still not working even implemented same as the link  http://stackoverflow.com/a/16995117/842214

**Comment by hamid97m** [comment]
wow
