### ISSUE TITLE
ScrollingTabContainerView error

### ISSUE THREAD

**Issue by JULI-ya** [JakeWharton/ActionBarSherlock#1037]
Hello!
I have problem with actionbarsherlok in my androia app.( I using ScrollingTabContainerView to create tabs. And when I select current tab second time, I have this error

java.lang.NullPointerException  at com.android.internal.widget.ScrollingTabContainerView$1.run(ScrollingTabContainerView.java:247)
    at android.os.Handler.handleCallback(Handler.java:615)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4745)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)

What is it? How I can correct it?

**Comment by JakeWharton** [comment]
> I using ScrollingTabContainerView to create tabs.

This is an internal widget. You should not be using it yourself.

**Comment by JULI-ya** [comment]
I am import com.actionbarsherlock.internal.widget.ScrollingTabContainerView; and create it tabsNavigator = new ScrollingTabContainerView(this);

I never using internal widget, but I have this error the same

**Comment by JakeWharton** [comment]
ScrollingTabsContainerView is not meant to be used directly. It is in an internal package of ABS.
