### ISSUE TITLE
SherlockPreferenceActivity

### ISSUE THREAD

**Issue by xWOLKx** [JakeWharton/ActionBarSherlock#260]
Hello everybody,
yesterday i added the sherlock preference plugin into my project.
But I have this problems, with emulator 1.6 (google api) the preference's page crash.

So from 2.1 all fine and works.

Always with emulator with 2.0 the app doesn't start, do: "force close", i think its a problem with action bar, its only mine problem?
I have do something wrong?

Thanks a lot!

**Comment by JakeWharton** [comment]
Can you paste a stack trace or provide an demo .zip that exhibits the problem?

**Comment by xWOLKx** [comment]
Sure!

```
02-14 08:30:15.916: D/dalvikvm(257): GC freed 3228 objects / 254216 bytes in 69ms
02-14 08:30:21.917: E/dalvikvm(257): Could not find method android.view.Window.hasFeature, referenced from method android.support.v4.app.SherlockPreferenceActivity.hasFeature
02-14 08:30:21.917: W/dalvikvm(257): VFY: unable to resolve virtual method 2568: Landroid/view/Window;.hasFeature (I)Z
02-14 08:30:21.917: W/dalvikvm(257): VFY:  rejecting opcode 0x6e at 0x000a
02-14 08:30:21.917: W/dalvikvm(257): VFY:  rejected Landroid/support/v4/app/SherlockPreferenceActivity;.hasFeature (J)Z
02-14 08:30:21.917: W/dalvikvm(257): Verifier rejected class Landroid/support/v4/app/SherlockPreferenceActivity;
02-14 08:30:21.917: W/dalvikvm(257): Class init failed in newInstance call (Lit/zonde/android/easytracks/PreferencesApp;)
02-14 08:30:21.917: D/AndroidRuntime(257): Shutting down VM
02-14 08:30:21.917: W/dalvikvm(257): threadid=3: thread exiting with uncaught exception (group=0x4001aa28)
02-14 08:30:21.917: E/AndroidRuntime(257): Uncaught handler: thread main exiting due to uncaught exception
02-14 08:30:21.997: E/AndroidRuntime(257): java.lang.VerifyError: android.support.v4.app.SherlockPreferenceActivity
02-14 08:30:21.997: E/AndroidRuntime(257):  at java.lang.Class.newInstanceImpl(Native Method)
02-14 08:30:21.997: E/AndroidRuntime(257):  at java.lang.Class.newInstance(Class.java:1472)
02-14 08:30:21.997: E/AndroidRuntime(257):  at android.app.Instrumentation.newActivity(Instrumentation.java:1097)
02-14 08:30:21.997: E/AndroidRuntime(257):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316)
02-14 08:30:21.997: E/AndroidRuntime(257):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417)
02-14 08:30:21.997: E/AndroidRuntime(257):  at android.app.ActivityThread.access$2100(ActivityThread.java:116)
02-14 08:30:21.997: E/AndroidRuntime(257):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
02-14 08:30:21.997: E/AndroidRuntime(257):  at android.os.Handler.dispatchMessage(Handler.java:99)
02-14 08:30:21.997: E/AndroidRuntime(257):  at android.os.Looper.loop(Looper.java:123)
02-14 08:30:21.997: E/AndroidRuntime(257):  at android.app.ActivityThread.main(ActivityThread.java:4203)
02-14 08:30:21.997: E/AndroidRuntime(257):  at java.lang.reflect.Method.invokeNative(Native Method)
02-14 08:30:21.997: E/AndroidRuntime(257):  at java.lang.reflect.Method.invoke(Method.java:521)
02-14 08:30:21.997: E/AndroidRuntime(257):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
02-14 08:30:21.997: E/AndroidRuntime(257):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
02-14 08:30:21.997: E/AndroidRuntime(257):  at dalvik.system.NativeStart.main(Native Method)
02-14 08:30:22.007: I/dalvikvm(257): threadid=7: reacting to signal 3
02-14 08:30:22.017: I/dalvikvm(257): Wrote stack trace to '/data/anr/traces.txt'
```

**Comment by JakeWharton** [comment]
I forgot to upload new versions of the plugins when I released v3.5.1. [Download](https://github.com/JakeWharton/ActionBarSherlock/downloads) the new versions and give it a try.

**Comment by JakeWharton** [comment]
Closing as i'm 99.99% sure that will fix it. Comment again if you still have a problem.

**Comment by xWOLKx** [comment]
Yes yes work perfectly!
i'm very sorry but I see the reply too late yesterday!

Great, THANKS A LOT
