### ISSUE TITLE
Indeterminate Progress crashes on Orange Barcelona

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#275]
The Indeterminate Progress sample crashes the Orange Barcelona running Android 2.2.2 with a 320x240 LDPI screen.

```
E/AndroidRuntime( 4300): FATAL EXCEPTION: main
E/AndroidRuntime( 4300): java.lang.IllegalArgumentException: bitmap size exceeds 32bits
E/AndroidRuntime( 4300):    at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime( 4300):    at android.graphics.Bitmap.createBitmap(Bitmap.java:481)
E/AndroidRuntime( 4300):    at android.view.View.buildDrawingCache(View.java:6448)
E/AndroidRuntime( 4300):    at android.view.ViewGroup.onAnimationStart(ViewGroup.java:1398)
E/AndroidRuntime( 4300):    at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
E/AndroidRuntime( 4300):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1512)
E/AndroidRuntime( 4300):    at android.view.View.draw(View.java:6753)
E/AndroidRuntime( 4300):    at android.widget.FrameLayout.draw(FrameLayout.java:352)
E/AndroidRuntime( 4300):    at android.view.ViewGroup.drawChild(ViewGroup.java:1785)
E/AndroidRuntime( 4300):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1512)
E/AndroidRuntime( 4300):    at android.view.ViewGroup.drawChild(ViewGroup.java:1783)
E/AndroidRuntime( 4300):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1512)
E/AndroidRuntime( 4300):    at android.view.ViewGroup.drawChild(ViewGroup.java:1783)
E/AndroidRuntime( 4300):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1512)
E/AndroidRuntime( 4300):    at android.view.View.draw(View.java:6753)
E/AndroidRuntime( 4300):    at android.widget.FrameLayout.draw(FrameLayout.java:352)
E/AndroidRuntime( 4300):    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1875)
E/AndroidRuntime( 4300):    at android.view.ViewRoot.draw(ViewRoot.java:1414)
E/AndroidRuntime( 4300):    at android.view.ViewRoot.performTraversals(ViewRoot.java:1170)
E/AndroidRuntime( 4300):    at android.view.ViewRoot.handleMessage(ViewRoot.java:1734)
E/AndroidRuntime( 4300):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4300):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 4300):    at android.app.ActivityThread.main(ActivityThread.java:4627)
E/AndroidRuntime( 4300):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4300):    at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime( 4300):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
E/AndroidRuntime( 4300):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/AndroidRuntime( 4300):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  138):   Force finishing activity com.actionbarsherlock.sample.demos/.IndeterminateProgress
W/ActivityManager(  138):   Force finishing activity com.actionbarsherlock.sample.demos/.SampleList
```

**Comment by ghost** [comment]
This is using the 4.0 Release Candidate.

**Comment by JakeWharton** [comment]
Dupe #273. Thanks for reporting, though.
