### ISSUE TITLE
NullPointerException when trying to select menu option after it was not visible

### ISSUE THREAD

**Issue by mattkranzler5** [JakeWharton/ActionBarSherlock#284]
I have a screen where by default a menu option is not visible. When changing to a different page in the view pager, the invalidateOptionsMenu() is called and it is set to visible. When trying to select the item, I am getting a NullPointerException. Here is the stack trace:

java.lang.NullPointerException
        at com.android.internal.view.menu.MenuItemImpl.toString(MenuItemImpl.java:490)
        at java.lang.StringBuilder.append(StringBuilder.java:202)
        at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:75)
        at android.support.v4.app.FragmentActivity.onOptionsItemSelected(FragmentActivity.java:283)
        at android.app.Activity.onMenuItemSelected(Activity.java:2502)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:632)
        at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:950)
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
        at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:490)
        at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:103)
        at android.view.View.performClick(View.java:3480)
        at android.view.View$PerformClick.run(View.java:13983)
        at android.os.Handler.handleCallback(Handler.java:605)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4340)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
I'm 99% sure this is a result of debug logging. I guess I should change it
since everyone is creating menu items without titles.
On Feb 17, 2012 8:58 PM, "mattkranzler5" <
reply@reply.github.com>
wrote:

**Comment by 1zaman** [comment]
This issue is not completely fixed - it needs to be fixed in SherlockFragmentActivity and ActionBarSherlockCompat also.

I am encountering it after updating to 4.3 because debug logs are enabled by default there.

See http://stackoverflow.com/questions/16057108/null-pointer-exception-showing-in-action-bar-sherlock-library

**Comment by berdon** [comment]
It looks like the issue is not adding a "title" attribute in XML to menu items.

**Comment by 1zaman** [comment]
Of course - the real bug is in Android MenuItemImpl toString() method which is delegated to title without a null check on it. The debug logging in ActionBarSherlock invokes this bug by implicitly calling toString() on the menu item through String concatenation. Replacing that with an explicit call to getTitle() or getTitleCondensed() fixes this issue.

**Comment by JakeWharton** [comment]
@IbraheemZaman Yeah. I'm going to update in the next release just to avoid this headache.
