### ISSUE TITLE
NPE in ActionMode Demo activity

### ISSUE THREAD

**Issue by mrenouf** [JakeWharton/ActionBarSherlock#288]
On. Android 2.3.3 "android-10" Emulator

This is seems to be a regression from the "official" RC1 demo apk.

```
02-18 11:37:58.505: I/ActionBarSherlock(1527): Registering ActionBarSherlockCompat with qualifier @com.actionbarsherlock.ActionBarSherlock$Implementation(api=7, dpi=-1)
02-18 11:37:58.515: I/ActionBarSherlock(1527): Registering ActionBarSherlockNative with qualifier @com.actionbarsherlock.ActionBarSherlock$Implementation(api=14, dpi=-1)
02-18 11:37:58.515: D/ActionBarSherlock(1527): [<ctor>] activity: com.actionbarsherlock.sample.demos.SampleList@40530f80, flags: 1
02-18 11:37:58.515: D/ActionBarSherlock(1527): [setContentView] layoutResId: 17367099
02-18 11:37:58.515: D/ActionBarSherlock(1527): [installDecor]
02-18 11:37:58.525: D/ActionBarSherlock(1527): [generateLayout]
02-18 11:37:58.525: D/ActionBarSherlock(1527): [requestFeature] featureId: 8
02-18 11:37:58.525: D/ActionBarSherlock(1527): [hasFeature] featureId: 8
02-18 11:37:58.525: D/ActionBarSherlock(1527): [hasFeature] featureId: 1
02-18 11:37:58.525: D/ActionBarSherlock(1527): [hasFeature] featureId: 9
02-18 11:37:58.545: I/dalvikvm(1527): Could not find method com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout.onHoverEvent, referenced from method com.actionbarsherlock.internal.widget.ActionBarContainer.onHoverEvent
02-18 11:37:58.545: W/dalvikvm(1527): VFY: unable to resolve virtual method 1640: Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineFrameLayout;.onHoverEvent (Landroid/view/MotionEvent;)Z
02-18 11:37:58.545: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x0000
02-18 11:37:58.545: D/dalvikvm(1527): VFY: dead code 0x0003-0004 in Lcom/actionbarsherlock/internal/widget/ActionBarContainer;.onHoverEvent (Landroid/view/MotionEvent;)Z
02-18 11:37:58.555: I/dalvikvm(1527): Could not find method android.widget.FrameLayout.getAlpha, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout.getAlpha
02-18 11:37:58.555: W/dalvikvm(1527): VFY: unable to resolve virtual method 544: Landroid/widget/FrameLayout;.getAlpha ()F
02-18 11:37:58.555: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000b
02-18 11:37:58.555: D/dalvikvm(1527): VFY: dead code 0x000e-000f in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineFrameLayout;.getAlpha ()F
02-18 11:37:58.555: I/dalvikvm(1527): Could not find method android.widget.FrameLayout.getTranslationY, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout.getTranslationY
02-18 11:37:58.555: W/dalvikvm(1527): VFY: unable to resolve virtual method 545: Landroid/widget/FrameLayout;.getTranslationY ()F
02-18 11:37:58.555: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000b
02-18 11:37:58.565: D/dalvikvm(1527): VFY: dead code 0x000e-000f in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineFrameLayout;.getTranslationY ()F
02-18 11:37:58.565: I/dalvikvm(1527): Could not find method android.widget.FrameLayout.setAlpha, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout.setAlpha
02-18 11:37:58.565: W/dalvikvm(1527): VFY: unable to resolve virtual method 547: Landroid/widget/FrameLayout;.setAlpha (F)V
02-18 11:37:58.565: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000a
02-18 11:37:58.565: D/dalvikvm(1527): VFY: dead code 0x000d-000d in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineFrameLayout;.setAlpha (F)V
02-18 11:37:58.565: I/dalvikvm(1527): Could not find method android.widget.FrameLayout.setTranslationY, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout.setTranslationY
02-18 11:37:58.565: W/dalvikvm(1527): VFY: unable to resolve virtual method 548: Landroid/widget/FrameLayout;.setTranslationY (F)V
02-18 11:37:58.565: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000a
02-18 11:37:58.565: D/dalvikvm(1527): VFY: dead code 0x000d-000d in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineFrameLayout;.setTranslationY (F)V
02-18 11:37:58.585: I/dalvikvm(1527): Could not find method com.actionbarsherlock.internal.view.menu.ActionMenuView.setAlpha, referenced from method com.actionbarsherlock.internal.widget.AbsActionBarView.animateToVisibility
02-18 11:37:58.585: W/dalvikvm(1527): VFY: unable to resolve virtual method 1923: Lcom/actionbarsherlock/internal/view/menu/ActionMenuView;.setAlpha (F)V
02-18 11:37:58.585: D/dalvikvm(1527): VFY: replacing opcode 0x6e at 0x0025
02-18 11:37:58.595: I/dalvikvm(1527): Could not find method android.view.ViewGroup.getAlpha, referenced from method com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.getAlpha
02-18 11:37:58.595: W/dalvikvm(1527): VFY: unable to resolve virtual method 469: Landroid/view/ViewGroup;.getAlpha ()F
02-18 11:37:58.595: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000b
02-18 11:37:58.595: D/dalvikvm(1527): VFY: dead code 0x000e-000f in Lcom/actionbarsherlock/internal/nineoldandroids/view/NineViewGroup;.getAlpha ()F
02-18 11:37:58.595: I/dalvikvm(1527): Could not find method android.view.ViewGroup.getTranslationX, referenced from method com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.getTranslationX
02-18 11:37:58.595: W/dalvikvm(1527): VFY: unable to resolve virtual method 473: Landroid/view/ViewGroup;.getTranslationX ()F
02-18 11:37:58.595: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000b
02-18 11:37:58.595: D/dalvikvm(1527): VFY: dead code 0x000e-000f in Lcom/actionbarsherlock/internal/nineoldandroids/view/NineViewGroup;.getTranslationX ()F
02-18 11:37:58.595: I/dalvikvm(1527): Could not find method android.view.ViewGroup.getTranslationY, referenced from method com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.getTranslationY
02-18 11:37:58.595: W/dalvikvm(1527): VFY: unable to resolve virtual method 474: Landroid/view/ViewGroup;.getTranslationY ()F
02-18 11:37:58.595: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000b
02-18 11:37:58.595: D/dalvikvm(1527): VFY: dead code 0x000e-000f in Lcom/actionbarsherlock/internal/nineoldandroids/view/NineViewGroup;.getTranslationY ()F
02-18 11:37:58.595: I/dalvikvm(1527): Could not find method android.view.ViewGroup.setAlpha, referenced from method com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.setAlpha
02-18 11:37:58.595: W/dalvikvm(1527): VFY: unable to resolve virtual method 479: Landroid/view/ViewGroup;.setAlpha (F)V
02-18 11:37:58.595: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000a
02-18 11:37:58.595: D/dalvikvm(1527): VFY: dead code 0x000d-000d in Lcom/actionbarsherlock/internal/nineoldandroids/view/NineViewGroup;.setAlpha (F)V
02-18 11:37:58.605: I/dalvikvm(1527): Could not find method android.view.ViewGroup.setTranslationX, referenced from method com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.setTranslationX
02-18 11:37:58.605: W/dalvikvm(1527): VFY: unable to resolve virtual method 481: Landroid/view/ViewGroup;.setTranslationX (F)V
02-18 11:37:58.605: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000a
02-18 11:37:58.605: D/dalvikvm(1527): VFY: dead code 0x000d-000d in Lcom/actionbarsherlock/internal/nineoldandroids/view/NineViewGroup;.setTranslationX (F)V
02-18 11:37:58.605: I/dalvikvm(1527): Could not find method android.view.ViewGroup.setTranslationY, referenced from method com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.setTranslationY
02-18 11:37:58.605: W/dalvikvm(1527): VFY: unable to resolve virtual method 482: Landroid/view/ViewGroup;.setTranslationY (F)V
02-18 11:37:58.605: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000a
02-18 11:37:58.605: D/dalvikvm(1527): VFY: dead code 0x000d-000d in Lcom/actionbarsherlock/internal/nineoldandroids/view/NineViewGroup;.setTranslationY (F)V
02-18 11:37:58.625: I/dalvikvm(1527): Could not find method com.actionbarsherlock.internal.widget.ActionBarView$HomeView.onHoverEvent, referenced from method com.actionbarsherlock.internal.widget.ActionBarView$HomeView.dispatchHoverEvent
02-18 11:37:58.625: W/dalvikvm(1527): VFY: unable to resolve virtual method 2481: Lcom/actionbarsherlock/internal/widget/ActionBarView$HomeView;.onHoverEvent (Landroid/view/MotionEvent;)Z
02-18 11:37:58.625: D/dalvikvm(1527): VFY: replacing opcode 0x6e at 0x0000
02-18 11:37:58.625: D/dalvikvm(1527): VFY: dead code 0x0003-0004 in Lcom/actionbarsherlock/internal/widget/ActionBarView$HomeView;.dispatchHoverEvent (Landroid/view/MotionEvent;)Z
02-18 11:37:58.625: I/dalvikvm(1527): Could not find method android.widget.FrameLayout.onPopulateAccessibilityEvent, referenced from method com.actionbarsherlock.internal.widget.ActionBarView$HomeView.onPopulateAccessibilityEvent
02-18 11:37:58.625: W/dalvikvm(1527): VFY: unable to resolve virtual method 546: Landroid/widget/FrameLayout;.onPopulateAccessibilityEvent (Landroid/view/accessibility/AccessibilityEvent;)V
02-18 11:37:58.625: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x0006
02-18 11:37:58.665: D/ActionBarSherlock(1527): [hasFeature] featureId: 5
02-18 11:37:58.675: D/ActionBarSherlock(1527): [hasFeature] featureId: 2
02-18 11:37:58.675: D/ActionBarSherlock(1527): [hasFeature] featureId: 5
02-18 11:37:58.675: I/ActionBarSherlock(1527): Parsing AndroidManifest.xml for com.actionbarsherlock.sample.demos.SampleList
02-18 11:37:58.675: D/ActionBarSherlock(1527): Got <application>
02-18 11:37:58.675: D/ActionBarSherlock(1527): debuggable: true
02-18 11:37:58.675: D/ActionBarSherlock(1527): icon: @2130837599
02-18 11:37:58.675: D/ActionBarSherlock(1527): label: @2131361795
02-18 11:37:58.675: D/ActionBarSherlock(1527): Got <activity>
02-18 11:37:58.675: D/ActionBarSherlock(1527): name: .SampleList
02-18 11:37:58.675: D/ActionBarSherlock(1527): label: @2131361796
02-18 11:37:58.675: D/ActionBarSherlock(1527): theme: @2131427387
02-18 11:37:58.675: I/ActionBarSherlock(1527): Returning 0
02-18 11:37:58.735: D/ActionBarSherlock(1527): [initActionBar]
02-18 11:37:58.735: D/ActionBarSherlock(1527): [hasFeature] featureId: 8
02-18 11:37:58.735: D/ActionBarSherlock(1527): [hasFeature] featureId: 1
02-18 11:37:58.735: D/ActionBarSherlock(1527): [dispatchOnPostCreate]
02-18 11:37:58.735: D/ActionBarSherlock(1527): [dispatchTitleChanged] title: ABS: Demos, color: 0
02-18 11:37:58.735: D/ActionBarSherlock(1527): [dispatchPostResume]
02-18 11:37:58.896: D/ActionBarSherlock(1527): [dispatchInvalidateOptionsMenu]
02-18 11:37:58.916: I/dalvikvm(1527): Could not find method android.view.ViewConfiguration.hasPermanentMenuKey, referenced from method com.actionbarsherlock.internal.view.menu.ActionMenuPresenter.reserveOverflow
02-18 11:37:58.916: W/dalvikvm(1527): VFY: unable to resolve virtual method 457: Landroid/view/ViewConfiguration;.hasPermanentMenuKey ()Z
02-18 11:37:58.916: D/dalvikvm(1527): VFY: replacing opcode 0x6e at 0x002a
02-18 11:37:58.916: D/dalvikvm(1527): VFY: dead code 0x002d-0033 in Lcom/actionbarsherlock/internal/view/menu/ActionMenuPresenter;.reserveOverflow (Landroid/content/Context;)Z
02-18 11:37:58.966: I/dalvikvm(1527): Could not find method android.view.View.jumpDrawablesToCurrentState, referenced from method com.actionbarsherlock.internal.view.menu.BaseMenuPresenter.updateMenuView
02-18 11:37:58.966: W/dalvikvm(1527): VFY: unable to resolve virtual method 427: Landroid/view/View;.jumpDrawablesToCurrentState ()V
02-18 11:37:58.966: D/dalvikvm(1527): VFY: replacing opcode 0x6e at 0x0056
02-18 11:37:58.966: D/ActionBarSherlock(1527): [callbackCreateOptionsMenu]
02-18 11:37:58.966: D/ActionBarSherlock(1527): [callbackCreateOptionsMenu] returning true
02-18 11:37:58.966: D/ActionBarSherlock(1527): [callbackPrepareOptionsMenu]
02-18 11:37:58.966: D/ActionBarSherlock(1527): [callbackPrepareOptionsMenu] returning true
02-18 11:37:58.966: W/KeyCharacterMap(1527): No keyboard for id -1
02-18 11:37:58.966: W/KeyCharacterMap(1527): Using default keymap: /system/usr/keychars/qwerty.kcm.bin
02-18 11:37:58.976: I/dalvikvm(1527): Could not find method com.actionbarsherlock.internal.view.menu.ActionMenuItemView.onHoverEvent, referenced from method com.actionbarsherlock.internal.view.menu.ActionMenuItemView.dispatchHoverEvent
02-18 11:37:58.986: W/dalvikvm(1527): VFY: unable to resolve virtual method 1788: Lcom/actionbarsherlock/internal/view/menu/ActionMenuItemView;.onHoverEvent (Landroid/view/MotionEvent;)Z
02-18 11:37:58.986: D/dalvikvm(1527): VFY: replacing opcode 0x6e at 0x0006
02-18 11:37:58.986: D/dalvikvm(1527): VFY: dead code 0x0009-0009 in Lcom/actionbarsherlock/internal/view/menu/ActionMenuItemView;.dispatchHoverEvent (Landroid/view/MotionEvent;)Z
02-18 11:37:58.986: I/dalvikvm(1527): Could not find method android.widget.LinearLayout.onPopulateAccessibilityEvent, referenced from method com.actionbarsherlock.internal.view.menu.ActionMenuItemView.onPopulateAccessibilityEvent
02-18 11:37:58.986: W/dalvikvm(1527): VFY: unable to resolve virtual method 596: Landroid/widget/LinearLayout;.onPopulateAccessibilityEvent (Landroid/view/accessibility/AccessibilityEvent;)V
02-18 11:37:58.986: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x0006
02-18 11:37:59.086: D/dalvikvm(1527): GC_EXTERNAL_ALLOC freed 207K, 51% free 2735K/5575K, external 2070K/2137K, paused 30ms
02-18 11:37:59.136: D/dalvikvm(1527): GC_EXTERNAL_ALLOC freed 8K, 52% free 2727K/5575K, external 2285K/2744K, paused 29ms
02-18 11:38:04.046: D/ActionBarSherlock(1527): [dispatchPause]
02-18 11:38:04.076: D/ActionBarSherlock(1527): [<ctor>] activity: com.actionbarsherlock.sample.demos.ActionModes@4050e7f8, flags: 1
02-18 11:38:04.076: D/ActionBarSherlock(1527): [setContentView] layoutResId: 2130903056
02-18 11:38:04.076: D/ActionBarSherlock(1527): [installDecor]
02-18 11:38:04.076: D/ActionBarSherlock(1527): [generateLayout]
02-18 11:38:04.076: D/ActionBarSherlock(1527): [requestFeature] featureId: 8
02-18 11:38:04.076: D/ActionBarSherlock(1527): [hasFeature] featureId: 8
02-18 11:38:04.076: D/ActionBarSherlock(1527): [hasFeature] featureId: 1
02-18 11:38:04.076: D/ActionBarSherlock(1527): [hasFeature] featureId: 9
02-18 11:38:04.126: D/ActionBarSherlock(1527): [hasFeature] featureId: 5
02-18 11:38:04.126: D/ActionBarSherlock(1527): [hasFeature] featureId: 2
02-18 11:38:04.126: D/ActionBarSherlock(1527): [hasFeature] featureId: 5
02-18 11:38:04.126: I/ActionBarSherlock(1527): Parsing AndroidManifest.xml for com.actionbarsherlock.sample.demos.ActionModes
02-18 11:38:04.126: D/ActionBarSherlock(1527): Got <application>
02-18 11:38:04.126: D/ActionBarSherlock(1527): debuggable: true
02-18 11:38:04.136: D/ActionBarSherlock(1527): icon: @2130837599
02-18 11:38:04.136: D/ActionBarSherlock(1527): label: @2131361795
02-18 11:38:04.136: D/ActionBarSherlock(1527): Got <activity>
02-18 11:38:04.136: D/ActionBarSherlock(1527): name: .SampleList
02-18 11:38:04.136: D/ActionBarSherlock(1527): Got <activity>
02-18 11:38:04.136: D/ActionBarSherlock(1527): name: .ActionModes
02-18 11:38:04.136: D/ActionBarSherlock(1527): label: @2131361797
02-18 11:38:04.136: I/ActionBarSherlock(1527): Returning 0
02-18 11:38:04.165: D/ActionBarSherlock(1527): [initActionBar]
02-18 11:38:04.165: D/ActionBarSherlock(1527): [hasFeature] featureId: 8
02-18 11:38:04.165: D/ActionBarSherlock(1527): [hasFeature] featureId: 1
02-18 11:38:04.165: D/ActionBarSherlock(1527): [dispatchOnPostCreate]
02-18 11:38:04.165: D/ActionBarSherlock(1527): [dispatchTitleChanged] title: Action Modes, color: 0
02-18 11:38:04.165: D/ActionBarSherlock(1527): [dispatchPostResume]
02-18 11:38:04.275: D/ActionBarSherlock(1527): [dispatchInvalidateOptionsMenu]
02-18 11:38:04.275: D/ActionBarSherlock(1527): [callbackCreateOptionsMenu]
02-18 11:38:04.286: D/ActionBarSherlock(1527): [callbackCreateOptionsMenu] returning true
02-18 11:38:04.286: D/ActionBarSherlock(1527): [callbackPrepareOptionsMenu]
02-18 11:38:04.286: D/ActionBarSherlock(1527): [callbackPrepareOptionsMenu] returning true
02-18 11:38:04.286: W/KeyCharacterMap(1527): No keyboard for id -1
02-18 11:38:04.286: W/KeyCharacterMap(1527): Using default keymap: /system/usr/keychars/qwerty.kcm.bin
02-18 11:38:04.345: D/dalvikvm(1527): GC_EXTERNAL_ALLOC freed 45K, 51% free 2784K/5575K, external 3615K/4191K, paused 26ms
02-18 11:38:04.631: D/ActionBarSherlock(1527): [dispatchStop]
02-18 11:38:06.525: D/ActionBarSherlock(1527): [initActionBar]
02-18 11:38:06.525: I/dalvikvm(1527): Could not find method android.widget.LinearLayout.<init>, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineLinearLayout.<init>
02-18 11:38:06.525: W/dalvikvm(1527): VFY: unable to resolve direct method 581: Landroid/widget/LinearLayout;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;I)V
02-18 11:38:06.525: D/dalvikvm(1527): VFY: replacing opcode 0x70 at 0x0000
02-18 11:38:06.536: D/dalvikvm(1527): VFY: dead code 0x0003-000f in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineLinearLayout;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;I)V
02-18 11:38:06.536: I/dalvikvm(1527): Could not find method android.widget.LinearLayout.getAlpha, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineLinearLayout.getAlpha
02-18 11:38:06.536: W/dalvikvm(1527): VFY: unable to resolve virtual method 585: Landroid/widget/LinearLayout;.getAlpha ()F
02-18 11:38:06.536: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000b
02-18 11:38:06.536: D/dalvikvm(1527): VFY: dead code 0x000e-000f in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineLinearLayout;.getAlpha ()F
02-18 11:38:06.536: I/dalvikvm(1527): Could not find method android.widget.LinearLayout.getTranslationX, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineLinearLayout.getTranslationX
02-18 11:38:06.536: W/dalvikvm(1527): VFY: unable to resolve virtual method 588: Landroid/widget/LinearLayout;.getTranslationX ()F
02-18 11:38:06.536: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000b
02-18 11:38:06.536: D/dalvikvm(1527): VFY: dead code 0x000e-000f in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineLinearLayout;.getTranslationX ()F
02-18 11:38:06.536: I/dalvikvm(1527): Could not find method android.widget.LinearLayout.setAlpha, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineLinearLayout.setAlpha
02-18 11:38:06.536: W/dalvikvm(1527): VFY: unable to resolve virtual method 597: Landroid/widget/LinearLayout;.setAlpha (F)V
02-18 11:38:06.536: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000a
02-18 11:38:06.536: D/dalvikvm(1527): VFY: dead code 0x000d-000d in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineLinearLayout;.setAlpha (F)V
02-18 11:38:06.536: I/dalvikvm(1527): Could not find method android.widget.LinearLayout.setTranslationX, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineLinearLayout.setTranslationX
02-18 11:38:06.536: W/dalvikvm(1527): VFY: unable to resolve virtual method 601: Landroid/widget/LinearLayout;.setTranslationX (F)V
02-18 11:38:06.536: D/dalvikvm(1527): VFY: replacing opcode 0x6f at 0x000a
02-18 11:38:06.536: D/dalvikvm(1527): VFY: dead code 0x000d-000d in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineLinearLayout;.setTranslationX (F)V
02-18 11:38:06.655: E/PropertyValuesHolder(1527): Couldn't find setter property alpha for ActionMenuView with value type float
02-18 11:38:06.655: E/PropertyValuesHolder(1527): ActionMenuView - Couldn't find no-arg method for property alpha: java.lang.NoSuchMethodException: getAlpha
02-18 11:38:06.655: D/AndroidRuntime(1527): Shutting down VM
02-18 11:38:06.655: W/dalvikvm(1527): threadid=1: thread exiting with uncaught exception (group=0x40015560)
02-18 11:38:06.665: E/AndroidRuntime(1527): FATAL EXCEPTION: main
02-18 11:38:06.665: E/AndroidRuntime(1527): java.lang.NullPointerException
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.nineoldandroids.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:515)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.nineoldandroids.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:386)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:539)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:929)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:952)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.nineoldandroids.animation.ObjectAnimator.start(ObjectAnimator.java:364)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.nineoldandroids.animation.AnimatorSet$DependencyListener.startIfReady(AnimatorSet.java:699)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.nineoldandroids.animation.AnimatorSet$DependencyListener.onAnimationStart(AnimatorSet.java:668)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:938)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:952)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.nineoldandroids.animation.ObjectAnimator.start(ObjectAnimator.java:364)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.nineoldandroids.animation.AnimatorSet.start(AnimatorSet.java:501)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.widget.AbsActionBarView.animateToVisibility(AbsActionBarView.java:169)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.app.ActionBarImpl.animateToMode(ActionBarImpl.java:628)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.app.ActionBarImpl.startActionMode(ActionBarImpl.java:405)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.startActionMode(ActionBarSherlockCompat.java:163)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.app.SherlockActivity.startActionMode(SherlockActivity.java:41)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.actionbarsherlock.sample.demos.ActionModes$1.onClick(ActionModes.java:40)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at android.view.View.performClick(View.java:2485)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at android.view.View$PerformClick.run(View.java:9080)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at android.os.Handler.handleCallback(Handler.java:587)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at android.os.Handler.dispatchMessage(Handler.java:92)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at android.os.Looper.loop(Looper.java:123)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at android.app.ActivityThread.main(ActivityThread.java:3683)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at java.lang.reflect.Method.invokeNative(Native Method)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at java.lang.reflect.Method.invoke(Method.java:507)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
02-18 11:38:06.665: E/AndroidRuntime(1527):     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by JakeWharton** [comment]
The problem here is that I've dropped using `IcsLinearLayout` for `ActionMenuView`'s parent as it was causing problems with measurement and it was not updating properly when subsequent calls to `invalidateOptionsMenu` were being made (e.g., by `FragmentManagerImpl` on any fragment change). By doing this we've lost the methods that enabled animation of translate and alpha properties on pre-3.0.

I need to figure out a way to emulate the dividers of ICS's `LinearLayout` without having to recreate the entire class.

If you want a temporary solution to this you can change `ActionMenuView` to extend from `NineLinearLayout` which will re-enable animation. I should probably push that into the working branch for now too...

**Comment by svenmeier** [comment]
Thanks for the tip, extending from NineLinearLayout works as a workaround.
