### ISSUE TITLE
Crash with Menu up and rotate device

### ISSUE THREAD

**Issue by Scott1234Abc** [JakeWharton/ActionBarSherlock#290]
RC1

Steps:
1. Derived activity from FragmentActivity (from the support snapshot jar).
2. Added a single item menu and inflate it in onCreateOptionsMenu with the supportMenuInflater.
3. Run the app
4. Bring up the menu
5. Rotate device with the menu up results in an NPE.

  Crash happens on this call in ActionBarSherlock.java (crashes inside onPreparePanel)
    protected final boolean callbackPrepareOptionsMenu(Menu menu) {
... 
            result = listener.onPreparePanel(Window.FEATURE_OPTIONS_PANEL, null, menu);
...
    }

Partial stack trace:
java.lang.NullPointerException
    at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:324)
    at com.actionbarsherlock.ActionBarSherlock.callbackPrepareOptionsMenu(ActionBarSherlock.java:464)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchPrepareOptionsMenu(ActionBarSherlockCompat.java:389)
    at android.support.v4.app.FragmentActivity.onPrepareOptionsMenu(FragmentActivity.java:278)
    at android.app.Activity.onPreparePanel(Activity.java:2233)

Just noticed in debugging that the "menu" parameter passed into this method in this scenario is "null" which I guess is the problem.

**Comment by JakeWharton** [comment]
Does the item have a title?
On Feb 18, 2012 9:44 AM, "Scott1234Abc" <
reply@reply.github.com>
wrote:

**Comment by Scott1234Abc** [comment]
Sorry - my bad, false alarm.  Had reverted to a prior version and forgot. RC1 is fine in this case.
