### ISSUE TITLE
Crash on 2.1 with screen rotation

### ISSUE THREAD

**Issue by doncung** [JakeWharton/ActionBarSherlock#301]
I tried this on an AT&T captivate and a nexus one with a 2.1 installed, and both crashed. This does not appear to happen on 2.2 or later devices I've tried, but possibly may happen on earlier devices.
Here's the relevant log info:

02-23 14:14:53.469: E/AndroidRuntime(4081): Uncaught handler: thread main exiting due to uncaught exception
02-23 14:14:53.544: E/AndroidRuntime(4081): java.lang.NullPointerException
02-23 14:14:53.544: E/AndroidRuntime(4081):     at com.actionbarsherlock.internal.widget.AbsActionBarView.onConfigurationChanged(AbsActionBarView.java:77)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at com.actionbarsherlock.internal.app.ActionBarImpl.onConfigurationChanged(ActionBarImpl.java:185)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchConfigurationChanged(ActionBarSherlockCompat.java:204)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at android.support.v4.app.FragmentActivity.onConfigurationChanged(FragmentActivity.java:453)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at com.box.android.activities.phone.MainPhone.onConfigurationChanged(MainPhone.java:120)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:3734)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:3803)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1936)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at android.os.Handler.dispatchMessage(Handler.java:99)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at android.os.Looper.loop(Looper.java:123)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at android.app.ActivityThread.main(ActivityThread.java:4363)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at java.lang.reflect.Method.invokeNative(Native Method)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at java.lang.reflect.Method.invoke(Method.java:521)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
02-23 14:14:53.544: E/AndroidRuntime(4081):     at dalvik.system.NativeStart.main(Native Method)

**Comment by doncung** [comment]
Just tried out the lastest now and looks like this was fixed at some point with all the changes.
