### ISSUE TITLE
No android:showAsAction attribute on submenu items crashes MenuInflater

### ISSUE THREAD

**Issue by yukuku** [JakeWharton/ActionBarSherlock#317]
Using post-RC1, commit 17cd662d5d10583cbfc8ec09e446ab45e498dff0 
Doesn't happen on RC1.

My menu XML file is:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:id="@+id/menuNavigate" android:icon="@drawable/ic_menu_navigate" android:showAsAction="always" android:title="Navigation Menu" android:orderInCategory="9">
        <menu>
            <item android:id="@+id/menuH" android:title="H" />
            <item android:id="@+id/menuE" android:title="E" />
            <item android:id="@+id/menuM" android:title="M"/>
            <item android:id="@+id/menuA" android:title="A" />
            <item android:id="@+id/menuV" android:title="V" />
            <item android:id="@+id/menuB" android:title="B" />
        </menu>
    </item>
</menu>
```

When I inflate it using getSupportMenuInflater(), I got the below error.

If I add showAsAction to the submenu items, it no longer crashes, for example:

``` xml
<item android:id="@+id/menuH" android:title="H" android:showAsAction="never" />
```

Logcat when error happens:

```
02-29 16:03:46.713: E/AndroidRuntime(14202): java.lang.NumberFormatException: unable to parse '@16973911' as integer
02-29 16:03:46.713: E/AndroidRuntime(14202):    at java.lang.Integer.parse(Integer.java:383)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at java.lang.Integer.parseInt(Integer.java:372)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:122)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at android.content.res.TypedArray.getInt(TypedArray.java:254)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at com.actionbarsherlock.view.MenuInflater$MenuState.readItem(MenuInflater.java:353)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at com.actionbarsherlock.view.MenuInflater.parseMenu(MenuInflater.java:146)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at com.actionbarsherlock.view.MenuInflater.parseMenu(MenuInflater.java:152)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at com.actionbarsherlock.view.MenuInflater.inflate(MenuInflater.java:96)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at com.myapp.ac.MainActivity.onCreateOptionsMenu(MainActivity.java:70)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at com.actionbarsherlock.app.SherlockFragmentActivity.onCreatePanelMenu(SherlockFragmentActivity.java:225)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:553)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:463)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:269)
02-29 16:03:46.713: E/AndroidRuntime(14202):    at com.actionbarsherlock.internal.ActionBarSherlockCompat$1.run(ActionBarSherlockCompat.java:968)
```

Thanks for all the good work!

**Comment by JakeWharton** [comment]
Blame that @SimonVT for "fixing" menu inflater :)

I'll have a look, thanks for the report.

**Comment by JakeWharton** [comment]
Out of curiosity, what version of Android did this happen on?

**Comment by Sleepybear** [comment]
Also crashes for a normal menu item when android:showAsAction is set on a GB emulator.

```
java.lang.NumberFormatException: unable to parse '@16973911' as integer
        at java.lang.Integer.parse(Integer.java:383)
        at java.lang.Integer.parseInt(Integer.java:372)
        at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:122)
        at android.content.res.TypedArray.getInt(TypedArray.java:254)
        at com.actionbarsherlock.view.MenuInflater$MenuState.readItem(MenuInflater.java:353)
        at com.actionbarsherlock.view.MenuInflater.parseMenu(MenuInflater.java:146)
        at com.actionbarsherlock.view.MenuInflater.inflate(MenuInflater.java:96)
        at us.sleepybear.android.mpgcalcpro.MainActivity.onCreateOptionsMenu(MainActivity.java:59)
        at com.actionbarsherlock.app.SherlockFragmentActivity.onCreatePanelMenu(SherlockFragmentActivity.java:225)
        at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:553)
        at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:463)
        at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:269)
        at com.actionbarsherlock.internal.ActionBarSherlockCompat$1.run(ActionBarSherlockCompat.java:968)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:3683)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by yukuku** [comment]
I'm using 2.3.7
CyanogenMod-7.1.0
on Nexus One.

**Comment by Sleepybear** [comment]
Believe this has to do with showAsAction not being an attribute until 3.0. When I change to:

``` java
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
                itemShowAsAction = a.getInt(R.styleable.SherlockMenuItem_android_showAsAction, -1);
            } else { // Grab it the old style way
                itemShowAsAction = attrs.getAttributeIntValue("http://schemas.android.com/apk/res/android", "showAsAction", -1);
            }
```

it no longer crashes on GB for when I have showAsAction set on a normal menu item. Was trying to maybe define it in a values-v5 folder, but since you're compiling against 4.0+ it complains that it already exists. The only other option I can think of is to use a non-prefixed attribute. 
Also works with your menu xml provided.

**Comment by SimonVT** [comment]
"Also crashes for a normal menu item when android:showAsAction is set on a GB emulator."
Wait, so it works on 2.1, but crashes on 2.3.3? oO That's strange.

**Comment by mykola-dev** [comment]
I have the same problem. None of my xml menu do not inflates correctly on 2.3.4 device and 2.3.5 x86 emulator. But all OK on 2.1 emulator and 4.0.3 emulator.

03-01 13:42:25.795: E/AndroidRuntime(2795):     at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:122)

**Comment by SimonVT** [comment]
Yeah, it only fails on GB, and only if no android:showAsAction is defined for an item. Apparantly it's trying to load a drawable instead oO

**Comment by mykola-dev** [comment]
Oh! I was inattentive. I was sure that I put android:showAsAction everywhere. But miss one item.
Anyway it really helps as temporary solution :) Thanks

**Comment by svenmeier** [comment]
The workaround works fine here.

Thanks

**Comment by Sleepybear** [comment]
Might be related to: https://github.com/android/platform_frameworks_base/blob/78996c9376ec8568e2bf9fbdee07f618936a7667/core/res/res/values/attrs.xml#L3616
Seems it used to be an enum then changed to be bit flags. Though shouldn't getInt() work with an enum?

**Comment by SimonVT** [comment]
No, the attributes were not available on GB.

**Comment by Sleepybear** [comment]
I was thinking it might have been put in GB as an enum but non-public and that's why it was having issues, but that doesn't really make sense either.

**Comment by iNoles** [comment]
it looks like there is no value for android:showAsAction then up to crash hard.

I am wondering this could work

``` java
if (a.hasValue(R.styleable.SherlockMenuItem_android_showAsAction)) {
    itemShowAsAction = a.getInt(R.styleable.SherlockMenuItem_android_showAsAction, -1);
} else {
   itemShowAsAction = -1;
}
```

**Comment by Sleepybear** [comment]
It has a value, it's just not an integer on <2.3 . I can't explain it
working on 2.1, I think that has something to do with the submenu. ABS4.0
defines it using the android: prefix within the Sherlock.ThemeMenu or
whatever it's named, so it would just reference the framework attribute if
it exists... unless I'm totally confused

On Thu, Mar 1, 2012 at 12:27 PM, Jonathan <
reply@reply.github.com

**Comment by iNoles** [comment]
Sleepybear, on OP post for menu XML, there is no android:showsAction = crash. if android:showsAction is exists, no crash.

According to TypedArray.hasValue, it supposed to determines whether there is an attribute at index. It seems that typedarray is looking for index that is not existed in 2.1.
