### ISSUE TITLE
NullPointerException in dispatchKeyEvent()

### ISSUE THREAD

**Issue by kaciula** [JakeWharton/ActionBarSherlock#466]
I get some crash reports for Galaxy Tab 7.7 (GT-P6800) on Android 3.2. Here is the stack trace:

java.lang.NullPointerException
at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchKeyEvent(ActionBarSherlockCompat.java:432)
at com.actionbarsherlock.app.SherlockFragmentActivity.dispatchKeyEvent(SherlockFragmentActivity.java:116)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1819)
at android.view.ViewRoot.deliverKeyEventPostIme(ViewRoot.java:2963)
at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2936)
at android.view.ViewRoot.handleMessage(ViewRoot.java:2102)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:132)
at android.app.ActivityThread.main(ActivityThread.java:4123)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:491)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Good catch, thanks. Fixed on `dev`, release this weekend.
