### ISSUE TITLE
IllegalStateException on MenuItemSelected

### ISSUE THREAD

**Issue by dmstocking** [JakeWharton/ActionBarSherlock#534]
I cannot recreate this bug that one of my users is having on any of my emulators or phones.

He says that "[it force] closes on clicking search". I have a search button on the actionbar. The problem is it never even reaches my code. I also have double checked that every fragment and every activity is a sherlockfragment/activity.

```
java.lang.IllegalStateException: Cannot interact with object designed for temporary instance passing. Make sure you using both SherlockFragmentActivity and SherlockFragment.
at com.actionbarsherlock.internal.view.menu.MenuItemMule.getItemId(MenuItemMule.java:71)
at android.app.Activity.onMenuItemSelected(Activity.java:2540)
at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:351)
at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:288)
at com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:586)
at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:78)
at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:191)
at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:958)
at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:514)
at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:99)
at android.view.View.performClick(View.java:4084)
at android.view.View$PerformClick.run(View.java:16966)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4745)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
```

I cannot for the life of me figured out what happened besides maybe the fact that this user has not updated my app in a while. I did update actionbarsherlock to 4.0.2 a while ago. So the only thing I can think of is that there is an issue in actionbarsherlock 4.0.2.

**Comment by JakeWharton** [comment]
Upgrade to ABS 4.1.0. Dupe #531.

**Comment by dmstocking** [comment]
Oh I didn't search closed issues. >.> sorry.
