### ISSUE TITLE
Missing drawable?

### ISSUE THREAD

**Issue by dsample** [JakeWharton/ActionBarSherlock#543]
Seems similar to #418. setContentView crashes one of my Activities with the following stacktrace (on 2.3.6). Works fine on 4.0.4, just the compatibility version that crashes. Not sure how to find the exact Drawable that's missing.

```
E/AndroidRuntime( 1127): FATAL EXCEPTION: main
E/AndroidRuntime( 1127): java.lang.RuntimeException: Unable to resume activity {uk.me.sample.android.ttrscoreboard/uk.me.sample.android.ttrscoreboard.RouteScoringActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class android.view.View
E/AndroidRuntime( 1127):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2120)
E/AndroidRuntime( 1127):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2135)
E/AndroidRuntime( 1127):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1668)
E/AndroidRuntime( 1127):    at android.app.ActivityThread.access$1500(ActivityThread.java:117)
E/AndroidRuntime( 1127):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
E/AndroidRuntime( 1127):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1127):    at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 1127):    at android.app.ActivityThread.main(ActivityThread.java:3683)
E/AndroidRuntime( 1127):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1127):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 1127):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
E/AndroidRuntime( 1127):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 1127):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1127): Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class android.view.View
E/AndroidRuntime( 1127):    at android.view.LayoutInflater.createView(LayoutInflater.java:518)
E/AndroidRuntime( 1127):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:549)
E/AndroidRuntime( 1127):    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:66)
E/AndroidRuntime( 1127):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
E/AndroidRuntime( 1127):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
E/AndroidRuntime( 1127):    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:707)
E/AndroidRuntime( 1127):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:619)
E/AndroidRuntime( 1127):    at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
E/AndroidRuntime( 1127):    at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
E/AndroidRuntime( 1127):    at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
E/AndroidRuntime( 1127):    at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:857)
E/AndroidRuntime( 1127):    at com.actionbarsherlock.app.SherlockActivity.setContentView(SherlockActivity.java:218)
E/AndroidRuntime( 1127):    at uk.me.sample.android.ttrscoreboard.RouteScoringActivity.onResume(RouteScoringActivity.java:46)
E/AndroidRuntime( 1127):    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1150)
E/AndroidRuntime( 1127):    at android.app.Activity.performResume(Activity.java:3832)
E/AndroidRuntime( 1127):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2110)
E/AndroidRuntime( 1127):    ... 12 more
E/AndroidRuntime( 1127): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 1127):    at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 1127):    at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
E/AndroidRuntime( 1127):    at android.view.LayoutInflater.createView(LayoutInflater.java:505)
E/AndroidRuntime( 1127):    ... 27 more
E/AndroidRuntime( 1127): Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x101032c a=-1}
E/AndroidRuntime( 1127):    at android.content.res.Resources.loadDrawable(Resources.java:1681)
E/AndroidRuntime( 1127):    at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
E/AndroidRuntime( 1127):    at android.view.View.<init>(View.java:1951)
E/AndroidRuntime( 1127):    at android.view.View.<init>(View.java:1899)
E/AndroidRuntime( 1127):    ... 30 more
```

**Comment by SimonVT** [comment]
It seems to be crashing when inflating your layout, not any of the ABS layouts. Are you sure this is an ABS issue?
https://github.com/JakeWharton/ActionBarSherlock/blob/master/library/src/com/actionbarsherlock/internal/ActionBarSherlockCompat.java#L857

**Comment by dsample** [comment]
Sorry, it was my error, trying to make my app work on earlier versions I didn't realise View wasn't valid in layouts. Would be helpful if the ADT Lint checks would pick that up.
