### ISSUE TITLE
Can't override onCreateOptionsMenu(Menu) on SherlockActivity on 2.2

### ISSUE THREAD

**Issue by goncalossilva** [JakeWharton/ActionBarSherlock#556]
In ABS 4.1.0, if I override onCreateOptionsMenu() with this simple code:

```
@Override
public boolean onCreateOptionsMenu(Menu menu) {
    MenuInflater inflater = getSupportMenuInflater();
    inflater.inflate(R.menu.home, menu);
    return true;
}
```

I can't start the app on Froyo. Everything works on Gingerbread, ICS and Jelly Bean. I've checked the imports and I'm using Menu, MenuInflater and MenuItem from ABS.

Here's the stack trace:

```
07-18 23:46:27.272: E/AndroidRuntime(2786): FATAL EXCEPTION: main
07-18 23:46:27.272: E/AndroidRuntime(2786): android.content.res.Resources$NotFoundException: Resource ID #0x7f020064
07-18 23:46:27.272: E/AndroidRuntime(2786):     at android.content.res.Resources.getValue(Resources.java:934)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at android.content.res.Resources.getDrawable(Resources.java:587)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:384)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.view.menu.ActionMenuItemView.initialize(ActionMenuItemView.java:128)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.view.menu.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:201)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:176)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.view.menu.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:187)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.view.menu.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:460)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1048)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:89)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.view.menu.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:215)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:247)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:946)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:969)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:524)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:273)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.actionbarsherlock.internal.ActionBarSherlockCompat$1.run(ActionBarSherlockCompat.java:988)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at android.os.Handler.handleCallback(Handler.java:587)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at android.os.Handler.dispatchMessage(Handler.java:92)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at android.os.Looper.loop(Looper.java:123)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at android.app.ActivityThread.main(ActivityThread.java:4627)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at java.lang.reflect.Method.invokeNative(Native Method)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at java.lang.reflect.Method.invoke(Method.java:521)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
07-18 23:46:27.272: E/AndroidRuntime(2786):     at dalvik.system.NativeStart.main(Native Method)
```

Am I doing something wrong?

**Comment by goncalossilva** [comment]
I'm an idiot. One of the menu items had its drawables exclusively in drawable-X-v9/ and drawable-X-v11/, causing the crash on 2.2. Sorry!
