### ISSUE TITLE
IllegalStateException at com.actionbarsherlock.widget.ActivityChooserView.onDetachedFromWindow

### ISSUE THREAD

**Issue by Digipom** [JakeWharton/ActionBarSherlock#557]
I've received a few reports of the following exception on the market, using Action Bar Sherlock 88fc341 and the Android Support Library v4, revision 9:

java.lang.IllegalStateException: Observer com.actionbarsherlock.widget.ActivityChooserView$1@405f4658 was not registered.
at android.database.Observable.unregisterObserver(Observable.java:64)
at com.actionbarsherlock.widget.ActivityChooserView.onDetachedFromWindow(Unknown Source)
at android.view.View.dispatchDetachedFromWindow(View.java:6173)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1164)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
at android.view.ViewRoot.dispatchDetachedFromWindow(ViewRoot.java:1746)
at android.view.ViewRoot.doDie(ViewRoot.java:2757)
at android.view.ViewRoot.die(ViewRoot.java:2727)
at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:218)
at android.view.Window$LocalWindowManager.removeViewImmediate(Window.java:436)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:2824)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:2929)
at android.app.ActivityThread.access$1600(ActivityThread.java:124)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:972)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3806)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)

I have configChanges:orientation on the activity. Unfortunately no more details as this is a market crash report.

Thanks!

**Comment by DHuckaby** [comment]
I have seen this also, but I don't use the configChanges manifest attribute.

**Comment by iNoles** [comment]
Real problem was  Observer com.actionbarsherlock.widget.ActivityChooserView$1@405f4658 was not registered.
That line called from android.database.Observable.unregisterObserver

**Comment by JakeWharton** [comment]
We wrap the code in a try/catch internally. Android sucks.

**Comment by JakeWharton** [comment]
Actually, we copy and paste the entire ShareActionProvider sources into our project, wrap that unregister in a try catch, change the `onCreateView` to return `null` (so it always shows in icon form), and delete `ActivityChooserView` things. I've also seen this crash on an ICS-only app using the native widget.

**Comment by DHuckaby** [comment]
@JakeWharton That is what I did in my app almost exactly, but before I caught the exception I saw it in the wild.

**Comment by Digipom** [comment]
So I got this without the configChanges:orientation as well. @JakeWharton I'm not sure I understand your comment; do I need to modify my project to fix this crash, or Action Bar Sherlock? Thanks!

**Comment by friscoMad** [comment]
You should also wrap with try catch registerObserver, it is not as usual but I was able to reproduce that error also.

**Comment by Digipom** [comment]
I can confirm try/catching and ignoring the exception for the two calls to unregisterObserver(mModelDataSetOberver) has fixed the issue for me. All the reported exceptions were in onDetachedFromWindow so maybe that's the important one.

**Comment by JakeWharton** [comment]
I'll wrap the other one too.

![](http://thediscipleproject.net/wp-content/uploads/2011/12/cartman_lame-1046.jpg)
