### ISSUE TITLE
"onClick"-attribute in menu.xml files

### ISSUE THREAD

**Issue by LukasKnuth** [JakeWharton/ActionBarSherlock#562]
I'm using the `onClick`-attribute in my menu files (under `/res/menu`). This works fine under ICS but throws an exception on my Android 2.3.5 device:

```
07-30 21:48:39.375: ERROR/AndroidRuntime(5864): FATAL EXCEPTION: main
android.view.InflateException: Couldn't resolve menu item onClick handler newTour in class org.knuth.biketrack.Main
at com.actionbarsherlock.view.MenuInflater$InflatedOnMenuItemClickListener.<init>(MenuInflater.java:219)
at com.actionbarsherlock.view.MenuInflater$MenuState.setItem(MenuInflater.java:424)
at com.actionbarsherlock.view.MenuInflater$MenuState.addItem(MenuInflater.java:460)
at com.actionbarsherlock.view.MenuInflater.parseMenu(MenuInflater.java:190)
at com.actionbarsherlock.view.MenuInflater.inflate(MenuInflater.java:112)
at org.knuth.biketrack.Main.onCreateOptionsMenu(Main.java:141)
at com.actionbarsherlock.app.SherlockActivity.onCreatePanelMenu(SherlockActivity.java:183)
at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:556)
at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:483)
at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:273)
at com.actionbarsherlock.internal.ActionBarSherlockCompat$1.run(ActionBarSherlockCompat.java:988)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:4385)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NoSuchMethodException
at java.lang.Class.getDeclaredMethods(Native Method)
at java.lang.ClassCache.getDeclaredPublicMethods(ClassCache.java:153)
at java.lang.ClassCache.getMethodsRecursive(ClassCache.java:216)
at java.lang.ClassCache.findMethods(ClassCache.java:175)
at java.lang.ClassCache.getMethods(ClassCache.java:167)
at java.lang.Class.getMethod(Class.java:961)
at com.actionbarsherlock.view.MenuInflater$InflatedOnMenuItemClickListener.<init>(MenuInflater.java:217)
... 19 more
```

The XML file looks like this:

```
<?xml version="1.0" encoding="utf-8"?>

<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:onClick="newTour"
          android:title="Create Tour"
          android:showAsAction="ifRoom|withText"
          android:icon="@android:drawable/ic_menu_add"
          />

</menu>
```

The method signature of `newTour()` looks like this:

```
    public void newTour(com.actionbarsherlock.view.MenuItem item)
```

This bug is present even after I merged the "dev"-branch into "master" to get the fix provided for [Issue 533](https://github.com/JakeWharton/ActionBarSherlock/issues/533). The fact that the correct class (`org.knuth.biketrack.Main`) is shown in the exception proofs, that this is not the source of error.

At this point, I'll need some clarification weather I can use the `onClick`-attribute or not, because the [Android Documentation](http://developer.android.com/guide/topics/resources/menu-resource.html) lines out that:

> Introduced in API Level 11.

**Comment by JakeWharton** [comment]
See: http://corner.squareup.com/2012/08/getting-to-the-bottom.html

I highly recommend you don't use onClick attributes due to their slowness and lack of compile-time safety. Sadly I'll have to remove these methods from ABS before releasing...

**Comment by JakeWharton** [comment]
Reverted that commit so this should be fixed. You still should not be doing this.
