### ISSUE TITLE
NoSuchFieldError in java.util.Locale.ROOT

### ISSUE THREAD

**Issue by Digipom** [JakeWharton/ActionBarSherlock#572]
Are there implementations of Gingerbread that do not have java.util.Locale.ROOT? I did get the following error reported in the market:

java.lang.NoSuchFieldError: java.util.Locale.ROOT
at com.actionbarsherlock.internal.widget.CapitalizingTextView.setTextCompat(Unknown Source)
at com.actionbarsherlock.internal.widget.ScrollingTabContainerView$TabView.update(Unknown Source)
at com.actionbarsherlock.internal.widget.ScrollingTabContainerView$TabView.init(Unknown Source)
at com.actionbarsherlock.internal.widget.ScrollingTabContainerView.createTabView(Unknown Source)
at com.actionbarsherlock.internal.widget.ScrollingTabContainerView.addTab(Unknown Source)
at com.actionbarsherlock.internal.app.ActionBarImpl.addTab(Unknown Source)
at com.actionbarsherlock.internal.app.ActionBarImpl.addTab(Unknown Source)

**Comment by JakeWharton** [comment]
Do you have more info on the device? The [API says it's Gingerbread+](https://developer.android.com/reference/java/util/Locale.html#ROOT).

**Comment by Digipom** [comment]
Unfortunately nothing. The code looked fine to me so I was surprised to see
that crash. Maybe some firmwares don't have it built in for some reason; a
try catch to default case might be good to have there.

Thanks!

**Comment by JakeWharton** [comment]
Lame. Will add to the next version. Thanks for the report.
