### ISSUE TITLE
java.lang.IllegalStateException: Observer is already registered

### ISSUE THREAD

**Issue by Digipom** [JakeWharton/ActionBarSherlock#573]
I'm not sure if you covered this in the fix for unregisterObserver, but since I noticed it locally I decided to report this, too. We might need to cover registerObserver as well...

java.lang.IllegalStateException: Observer com.actionbarsherlock.widget.ActivityChooserView$1@40597760 is already registered.
at android.database.Observable.registerObserver(Observable.java:44)
at com.actionbarsherlock.widget.ActivityChooserView.onAttachedToWindow(Unknown Source)
at android.view.View.dispatchAttachedToWindow(View.java:6156)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:1122)
at android.view.ViewGroup.addViewInner(ViewGroup.java:2011)
at android.view.ViewGroup.addView(ViewGroup.java:1871)
at android.view.ViewGroup.addView(ViewGroup.java:1828)
at com.actionbarsherlock.internal.view.menu.BaseMenuPresenter.addItemView(Unknown Source)
at com.actionbarsherlock.internal.view.menu.BaseMenuPresenter.updateMenuView(Unknown Source)
at com.actionbarsherlock.internal.view.menu.ActionMenuPresenter.updateMenuView(Unknown Source)
at com.actionbarsherlock.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(Unknown Source)
at com.actionbarsherlock.internal.view.menu.MenuBuilder.onItemsChanged(Unknown Source)
at com.actionbarsherlock.internal.view.menu.MenuBuilder.startDispatchingItemsChanged(Unknown Source)
at com.actionbarsherlock.internal.app.ActionBarImpl$ActionModeImpl.invalidate(Unknown Source)

**Comment by JakeWharton** [comment]
Dupe #557. Fixed on `dev`.
