### ISSUE TITLE
API level 10  bug?

### ISSUE THREAD

**Issue by crossle** [JakeWharton/ActionBarSherlock#577]
ava.lang.NullPointerException
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.a(SourceFile:665)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.setProgress(SourceFile:653)
    at com.actionbarsherlock.app.SherlockFragmentActivity.setSupportProgress(SourceFile:274)
    at pb.onProgressChanged(SourceFile:72)
    at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:365)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:3806)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
You need to provide more information about how to reproduce this or what even caused it. Closing until more info is available.

Also, don't obfuscate ABS code.
