### ISSUE TITLE
NPE when calling FragmentActivity.closeOptionsMenu in a theme without actionbar

### ISSUE THREAD

**Issue by rburgst** [JakeWharton/ActionBarSherlock#591]
We have an activity that uses a dialog theme on the tablet. Therefore there is no action bar. In such a case calling closeOptionsMenu() result in an NPE.

```
E/AndroidRuntime(25550): java.lang.NullPointerException
E/AndroidRuntime(25550):    at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchCloseOptionsMenu(ActionBarSherlockCompat.java:296)
E/AndroidRuntime(25550):    at com.actionbarsherlock.app.SherlockFragmentActivity.closeOptionsMenu(SherlockFragmentActivity.java:217)
```

The fix is pretty trivial:

ActionBarSherlockCompat:

``` java
    @Override
    public boolean dispatchCloseOptionsMenu() {
        if (DEBUG) Log.d(TAG, "[dispatchCloseOptionsMenu]");

        if (!isReservingOverflow()) {
            return false;
        }

        // prevent NPE
        if (wActionBar != null) {
            return wActionBar.hideOverflowMenu();
        } 
        return false;
    }
```

**Comment by JakeWharton** [comment]
Good catch. Thanks.
