### ISSUE TITLE
Observer com.actionbarsherlock.widget.ActivityChooserView$1@405501d0 was not registered.

### ISSUE THREAD

**Issue by dmarcato** [JakeWharton/ActionBarSherlock#595]
I've got this crash report from my application that is using ActionBarSherlock and I don't know what is causing it...

```
0   java.lang.IllegalStateException: Observer com.actionbarsherlock.widget.ActivityChooserView$1@405501d0 was not registered.
1       at android.database.Observable.unregisterObserver(Observable.java:64)
2       at com.actionbarsherlock.widget.ActivityChooserView.onDetachedFromWindow(ActivityChooserView.java:408)
3       at android.view.View.dispatchDetachedFromWindow(View.java:6170)
4       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1164)
5       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
6       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
7       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
8       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
9       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
10      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
11      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1162)
12      at android.view.ViewRoot.dispatchDetachedFromWindow(ViewRoot.java:1756)
13      at android.view.ViewRoot.doDie(ViewRoot.java:2767)
14      at android.view.ViewRoot.die(ViewRoot.java:2737)
15      at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:218)
16      at android.view.Window$LocalWindowManager.removeViewImmediate(Window.java:436)
17      at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:2701)
18      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:2806)
19      at android.app.ActivityThread.access$1600(ActivityThread.java:117)
20      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
21      at android.os.Handler.dispatchMessage(Handler.java:99)
22      at android.os.Looper.loop(Looper.java:130)
23      at android.app.ActivityThread.main(ActivityThread.java:3683)
24      at java.lang.reflect.Method.invokeNative(Native Method)
25      at java.lang.reflect.Method.invoke(Method.java:507)
26      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
27      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
28      at dalvik.system.NativeStart.main(Native Method)
```

Any ideas? :)

**Comment by JakeWharton** [comment]
Dupe #557. This is fixed on the `dev` branch.

**Comment by dmarcato** [comment]
Ok thanks!

**Comment by thunderousNinja** [comment]
Hey @JakeWharton, is this fixed on master branch yet? Or is it still on devo?

**Comment by JakeWharton** [comment]
Released.

**Comment by thunderousNinja** [comment]
@JakeWharton thanks man :+1:
