### ISSUE TITLE
Exception dispatching input event.

### ISSUE THREAD

**Issue by mandrachek** [JakeWharton/ActionBarSherlock#596]
I'm using 4.1.0 on a Nexus S running JB, and in trying to reproduce some subtle, hard to find issues with my app, I stumbled upon an exception coming from ABS while running monkey. This seems very similar, but subtly different from issue #531.  

``` java
09-04 14:26:15.140: E/InputEventReceiver(11206): Exception dispatching input event.
09-04 14:26:15.199: E/MessageQueue-JNI(11206): Exception in MessageQueue callback: handleReceiveCallback
09-04 14:26:15.269: E/MessageQueue-JNI(11206): java.lang.NullPointerException
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:78)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at com.actionbarsherlock.app.SherlockActivity.onOptionsItemSelected(SherlockActivity.java:148)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.app.Activity.onMenuItemSelected(Activity.java:2534)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at com.android.internal.widget.ActionBarView$3.onClick(ActionBarView.java:167)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.View.performClick(View.java:4084)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.View.onKeyUp(View.java:7669)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.KeyEvent.dispatch(KeyEvent.java:2633)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.View.dispatchKeyEvent(View.java:7086)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1354)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1892)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1369)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.app.Activity.dispatchKeyEvent(Activity.java:2356)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at com.actionbarsherlock.app.SherlockActivity.dispatchKeyEvent(SherlockActivity.java:116)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1819)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3575)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.ViewRootImpl.deliverKeyEvent(ViewRootImpl.java:3531)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3113)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4153)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4132)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4224)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.os.MessageQueue.nativePollOnce(Native Method)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.os.MessageQueue.next(MessageQueue.java:125)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.os.Looper.loop(Looper.java:124)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at android.app.ActivityThread.main(ActivityThread.java:4745)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at java.lang.reflect.Method.invokeNative(Native Method)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at java.lang.reflect.Method.invoke(Method.java:511)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
09-04 14:26:15.269: E/MessageQueue-JNI(11206):  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by iNoles** [comment]
According to source code for that file, final boolean result = callbackOptionsItemSelected(mMenu.findItem(item)) is Null

looks like something skipped dispatchCreateOptionsMenu

**Comment by mandrachek** [comment]
Would this be something in my code, or in ABS? The stack trace doesn't even tell me the activity that it was in at the time.

**Comment by rburgst** [comment]
Have the same issue. I can produce this issue quite easily with monkey test. The log tells me that the monkey manages to click an options menu multiple times and then there is a race condition on how fast the new activity comes up. 

In my case mMenu == null.

```
@Override
public boolean dispatchOptionsItemSelected(android.view.MenuItem item) {
    if (DEBUG) Log.d(TAG, "[dispatchOptionsItemSelected] item: " + item.getTitleCondensed());

    final boolean result = callbackOptionsItemSelected(mMenu.findItem(item));
    if (DEBUG) Log.d(TAG, "[dispatchOptionsItemSelected] returning " + result);
    return result;
}
```

From the log I see that 

```
[dispatchCreateOptionsMenu] menu: com.android.internal.view.menu.MenuBuilder@4195b3f0  => ACTIVITY A
[dispatchCreateOptionsMenu] returning true => ACTIVITY A
[dispatchPrepareOptionsMenu] menu: com.android.internal.view.menu.MenuBuilder@4195b3f0, => ACTIVITY A 
[dispatchPrepareOptionsMenu] returning true, => ACTIVITY A
[dispatchOptionsItemSelected] item: Menu Option, => ACTIVITY A
[dispatchOptionsItemSelected] returning true => ACTIVITY A
[dispatchOptionsItemSelected] item: Debug, => ACTIVITY A
[dispatchOptionsItemSelected] returning false => ACTIVITY A
[dispatchOptionsItemSelected] item: null, => ACTIVITY B => WTF??
```

I am also not entirely sure why item == null in that case. Havent analyzed further.

Proposed fix

```
@Override
public boolean dispatchOptionsItemSelected(android.view.MenuItem item) {
    if (DEBUG) Log.d(TAG, "[dispatchOptionsItemSelected] item: " + item.getTitleCondensed() + ", " + mActivity);

    // RBUR: fix for bug found by monkey test
    if (mMenu == null || item == null) {
        if (DEBUG) {
            Log.e(TAG, "[dispatchOptionsItemSelected] discarded stray selected event: " + item
                    + " for activity " + mActivity);
        }
            return false;
    }
    final boolean result = callbackOptionsItemSelected(mMenu.findItem(item));
    if (DEBUG) Log.d(TAG, "[dispatchOptionsItemSelected] returning " + result);
    return result;
}
```

**Comment by JulienDev** [comment]
I also have this issue with Monkey Test

**Comment by JakeWharton** [comment]
This is the home action item. We fixed this.
