### ISSUE TITLE
java.lang.NoSuchMethodError: android.view.ViewTreeObserver.removeGlobalOnLayoutListener

### ISSUE THREAD

**Issue by winterDroid** [JakeWharton/ActionBarSherlock#601]
Hello!

On Android 2.3.6 I've got with the Samsung GT-I9001 the following exception. Maybe you can find a solution for it or explain it to me. Thanks :-)

``` java
java.lang.NoSuchMethodError: android.view.ViewTreeObserver.removeGlobalOnLayoutListener
at com.actionbarsherlock.internal.view.menu.MenuPopupHelper.onDismiss(MenuPopupHelper.java:145)
at com.actionbarsherlock.internal.view.menu.ActionMenuPresenter$ActionButtonSubmenu.onDismiss(ActionMenuPresenter.java:681)
at android.widget.PopupWindow.dismiss(PopupWindow.java:1147)
at com.actionbarsherlock.internal.widget.IcsListPopupWindow.dismiss(IcsListPopupWindow.java:240)
at com.actionbarsherlock.internal.view.menu.MenuPopupHelper.dismiss(MenuPopupHelper.java:136)
at com.actionbarsherlock.internal.view.menu.MenuPopupHelper.onCloseMenu(MenuPopupHelper.java:273)
at com.actionbarsherlock.internal.view.menu.MenuBuilder.close(MenuBuilder.java:921)
at com.actionbarsherlock.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:896)
at com.actionbarsherlock.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:158)
at android.widget.AdapterView.performItemClick(AdapterView.java:284)
at android.widget.ListView.performItemClick(ListView.java:3701)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:1980)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by JakeWharton** [comment]
That method is available from API 1+ as [per the docs](https://developer.android.com/reference/android/view/ViewTreeObserver.html#removeGlobalOnLayoutListener%28android.view.ViewTreeObserver.OnGlobalLayoutListener%29). If Samsung removed it on the ROM for that device then there isn't much I can do about it. Sorry.
