### ISSUE TITLE
ActivityChooserView not registered

### ISSUE THREAD

**Issue by chrisjenx** [JakeWharton/ActionBarSherlock#637]
Seen this a couple of times reported over Bugsense:

When opening a keyboard in certain places, its not a high priority bug as i have never managed to forcibly reproduce it. 

Pre Android 3.0 - Devices older than a year (Wildfire, Desire, Gal 1 etc)

java.lang.IllegalStateException: Observer com.actionbarsherlock.widget.ActivityChooserView$1@45a4dcb0 was not registered.
at android.database.Observable.unregisterObserver(Observable.java:64)
at com.actionbarsherlock.widget.ActivityChooserView.onDetachedFromWindow(ActivityChooserView.java:408)
at android.view.View.dispatchDetachedFromWindow(View.java:5927)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1160)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1158)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1158)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1158)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1158)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1158)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1158)
at android.view.ViewRoot.dispatchDetachedFromWindow(ViewRoot.java:1570)
at android.view.ViewRoot.doDie(ViewRoot.java:2556)
at android.view.ViewRoot.die(ViewRoot.java:2526)
at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:218)
at android.view.Window$LocalWindowManager.removeViewImmediate(Window.java:436)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3505)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3606)
at android.app.ActivityThread.access$2300(ActivityThread.java:123)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1874)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4370)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Dupe #595. Fixed on `dev`.
