### ISSUE TITLE
got NullPointerException on SherlockFragmentActivity.invalidateOptionsMenu

### ISSUE THREAD

**Issue by kingori** [JakeWharton/ActionBarSherlock#652]
I'm using ABS 4.2.0 on GB(2.3.6) and got NullPointerException.

Stacktrace is like below. I've put 3 fragment on each tab and each tab has its own action menu item.

10-11 14:03:19.566: ERROR/AndroidRuntime(25214): FATAL EXCEPTION: main
        java.lang.NullPointerException
        at android.view.View.dispatchRestoreInstanceState(View.java:6326)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1211)
        at android.view.View.restoreHierarchyState(View.java:6310)
        at com.actionbarsherlock.internal.view.menu.MenuBuilder.restoreActionViewStates(MenuBuilder.java:361)
        at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:503)
        at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:272)
        at com.actionbarsherlock.app.SherlockFragmentActivity.invalidateOptionsMenu(SherlockFragmentActivity.java:150)
        at com.actionbarsherlock.app.SherlockFragmentActivity.supportInvalidateOptionsMenu(SherlockFragmentActivity.java:156)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1095)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:635)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1431)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:420)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3687)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by kingori** [comment]
This error occurs 
1. open activity with 3 tabs ( 3rd tab fragment has collapseActionView menu item)
2. select 2nd tab
3. press power button to turn screen off
4. press power button to turn screen on
5. screen shows 2nd tab
6. select 3rd tab and crash.

menu of 3rd tab is like below

<menu xmlns:android="http://schemas.android.com/apk/res/android" >

```
<item
    android:id="@id/menu_search"
    android:actionLayout="@layout/v_action_view_search"
    android:showAsAction="always|collapseActionView"
    android:title="@string/label_menu_search"
    android:icon="@drawable/ab_search"
    />
<item
    android:id="@+id/menu_add_friends"
    android:showAsAction="always"
    android:title="@string/label_menu_friend_add"
    android:icon="@drawable/ab_ymk"/>
```

</menu>

**Comment by SimonVT** [comment]
Please add a sample displaying this behavior to the known bugs project.

**Comment by xDragonZ** [comment]
`10-12 17:21:07.869: E/AndroidRuntime(29713): FATAL EXCEPTION: main
java.lang.NullPointerException
at android.view.View.dispatchRestoreInstanceState(View.java:6295)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1211)
at android.view.View.restoreHierarchyState(View.java:6279)
at com.actionbarsherlock.internal.view.menu.MenuBuilder.restoreActionViewStates(MenuBuilder.java:361)
at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:503)
at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:272)
at com.actionbarsherlock.app.SherlockFragmentActivity.invalidateOptionsMenu(SherlockFragmentActivity.java:150)
at com.evozi.apps.ui.activity.onNavigationItemSelected(activity.java:169)
at com.actionbarsherlock.internal.widget.ActionBarView$1.onItemSelected(ActionBarView.java:147)
at com.actionbarsherlock.internal.widget.IcsAdapterView.fireOnSelected(IcsAdapterView.java:861)
at com.actionbarsherlock.internal.widget.IcsAdapterView.access$2(IcsAdapterView.java:854)
at com.actionbarsherlock.internal.widget.IcsAdapterView$SelectionNotifier.run(IcsAdapterView.java:827)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3835)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
at dalvik.system.NativeStart.main(Native Method)`

Line 169 :
`invalidateOptionsMenu();`

inside 

`public boolean onNavigationItemSelected(int itemPosition, long itemId) {`

Using ABS 4.2.0 on GB(2.3.7) and got NullPointerException too.

 ActionBar.NAVIGATION_MODE_LIST

> SherlockFragmentActivity implements ActionBar.OnNavigationListener

Steps to reproduce :
- Open the application
- Press power button to turn screen off
- Leave a few seconds
- Press power button to turn screen on
- Select another navigation item in the list
- Application crash

**Comment by Richie97** [comment]
I'm having the same issue, anyone figure out what was going on here?

**Comment by iNoles** [comment]
on

```
// Restore action view state before we prepare. This gives apps
        // an opportunity to override frozen/restored state in onPrepare.
        if (mMenuFrozenActionViewState != null) {
            mMenu.restoreActionViewStates(mMenuFrozenActionViewState);
            mMenuFrozenActionViewState = null;
        }
```

When mMenu is NULL, CRASH!!! 

I noticed that stopDispatchingItemsChanged() can set mMenu to null.

**Comment by PeterRinc** [comment]
The same issue here. Using ABS 4.2.0 on GB (2.3.3) and got NullPointerException too.

Steps to reproduce:
- have activity with 3 tabs
- be on 1st tab
- press power button to turn screen off
- press power button to turn screen on
- screen shows 1st tab
- select 2nd tab (tab fragment has collapseActionView menu item)
- crash...

Stacktrace:

```
FATAL EXCEPTION: main
java.lang.NullPointerException
    at android.view.View.dispatchRestoreInstanceState(View.java:6273)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1211)
    at android.view.View.restoreHierarchyState(View.java:6257)
    at com.actionbarsherlock.internal.view.menu.MenuBuilder.restoreActionViewStates(MenuBuilder.java:361)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:503)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:272)
    at com.actionbarsherlock.app.SherlockFragmentActivity.invalidateOptionsMenu(SherlockFragmentActivity.java:150)
    at com.actionbarsherlock.app.SherlockFragmentActivity.supportInvalidateOptionsMenu(SherlockFragmentActivity.java:156)
    at android.support.v4.app.Fragment.setHasOptionsMenu(Fragment.java:708)
    at com.spica.asm.ui.TabLocationsFragment.onActivityCreated(TabLocationsFragment.java:51)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:891)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1080)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:622)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1416)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:420)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3683)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by burberius** [comment]
I had the same problem and the fix works for me.

**Comment by jpozuelo** [comment]
It works for me. Thanks!!

**Comment by goncalossilva** [comment]
Works for me too. Thanks!

**Comment by cesards** [comment]
Same here and solved too! Thanks! :-)

**Comment by pflammertsma** [comment]
I'm seeing the same stack trace as PeterRinc mentioned above, but on a Honeycomb 3.2 device (Samsung GT-P7300). As Peter shows, it originates from setHasOptionsMenu(). (I've applied fix #652, but that only targets pre-Honeycomb.)

**Comment by NiakJudge** [comment]
(@pflammertsma) 
I can reproduce the issue on on a Honeycomb  3.2 ( Motorola XOOM MZ601)
From setHasOptionsMenu() too.
Using ABS v4.3.1.

> FATAL EXCEPTION: main
> java.lang.NullPointerException
>   at android.view.View.dispatchRestoreInstanceState(View.java:8311)
>   at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2018)
>   at android.view.View.restoreHierarchyState(View.java:8295)
>   at com.actionbarsherlock.internal.view.menu.MenuBuilder.restoreActionViewStates(MenuBuilder.java:367)
>   at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:490)
>   at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:265)
>   at com.actionbarsherlock.app.SherlockFragmentActivity.invalidateOptionsMenu(SherlockFragmentActivity.java:150)
>   at com.actionbarsherlock.app.SherlockFragmentActivity.supportInvalidateOptionsMenu(SherlockFragmentActivity.java:156)
>   at android.support.v4.app.Fragment.setHasOptionsMenu(Fragment.java:763)

**Comment by jeffxchu** [comment]
Just a quick note. Yes, looks like it's still happening. 

```
java.lang.NullPointerException
at android.view.View.dispatchRestoreInstanceState(View.java:6335)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1297)
at android.view.View.restoreHierarchyState(View.java:6319)
at com.actionbarsherlock.internal.view.menu.MenuBuilder.restoreActionViewStates(SourceFile:361)
at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(SourceFile:503)
at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(SourceFile:272)
at com.actionbarsherlock.app.SherlockFragmentActivity.invalidateOptionsMenu(SourceFile:150)
at com.actionbarsherlock.app.SherlockFragmentActivity.supportInvalidateOptionsMenu(SourceFile:156)
at android.support.v4.app.Fragment.setHasOptionsMenu(SourceFile:763)
```

**Comment by deakjahn** [comment]
Very much so, I've just run into it on a 3.2 Galaxy Tab. Changing MenuBuilder:357 to

```
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.ICE_CREAM_SANDWICH && viewStates == null) {
```

seems to take care of it on the devices I have lying around but I can't vote for all of them out there for sure... :-)

**Comment by EurigJones** [comment]
I'm also seeing this with a "SmartTab 10" whatever that is! Not sure which Android version it's using though.
