### ISSUE TITLE
setHasOptionsMenu throws NullPointerException

### ISSUE THREAD

**Issue by o-antsiferov** [JakeWharton/ActionBarSherlock#695]
It happens sometimes (not every time) on android 2.3 in `Fragment#onCreate()` method when trying to call `setHasOptionsMenu(true)`:

```
11-12 12:45:29.112: E/AndroidRuntime(369): java.lang.NullPointerException
11-12 12:45:29.112: E/AndroidRuntime(369):  at android.view.View.dispatchRestoreInstanceState(View.java:6273)
11-12 12:45:29.112: E/AndroidRuntime(369):  at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1211)
11-12 12:45:29.112: E/AndroidRuntime(369):  at android.view.View.restoreHierarchyState(View.java:6257)
11-12 12:45:29.112: E/AndroidRuntime(369):  at com.actionbarsherlock.internal.view.menu.MenuBuilder.restoreActionViewStates(MenuBuilder.java:361)
11-12 12:45:29.112: E/AndroidRuntime(369):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:503)
11-12 12:45:29.112: E/AndroidRuntime(369):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:272)
11-12 12:45:29.112: E/AndroidRuntime(369):  at com.actionbarsherlock.app.SherlockFragmentActivity.invalidateOptionsMenu(SherlockFragmentActivity.java:150)
11-12 12:45:29.112: E/AndroidRuntime(369):  at com.actionbarsherlock.app.SherlockFragmentActivity.supportInvalidateOptionsMenu(SherlockFragmentActivity.java:156)
11-12 12:45:29.112: E/AndroidRuntime(369):  at android.support.v4.app.Fragment.setHasOptionsMenu(Fragment.java:712)
``
```

**Comment by Vandalko** [comment]
I think it's related to https://github.com/JakeWharton/ActionBarSherlock/issues/725. I've fixed this NPE in my project by modifying restoreActionViewStates method so it would not call View.restoreHierarchyState if bundle is NULL or view's id == View.NO_ID

**Comment by JakeWharton** [comment]
Dupe #686.
