### ISSUE TITLE
NullPointerException in ActionBarSherlockNative.dispatchOptionsItemSelected

### ISSUE THREAD

**Issue by Rittzz** [JakeWharton/ActionBarSherlock#701]
Device: Galaxy Nexus running Android 4.1.2

While running monkey ("adb shell monkey -p _package name here_ -v 3000" is the exact command we are using) we are running into a null pointer exception bug in the ABS library.  I've managed to reproduce this bug on both the latest versions of ABS (4.2.0 at the time of this writing) down to 4.1.0 and they all produce the same stack trace inside our app.

However, I have been unable to reproduce this bug running monkey on the sample ABS app so I'm wondering if we are doing something we aren't suppose to.

Stack Trace from Monkey using ABS 4.2.0:

Short Msg: java.lang.NullPointerException
Long Msg: java.lang.NullPointerException
Build Label: google/yakju/maguro:4.1.2/JZO54K/485486:user/release-keys
Build Changelist: 485486
Build Time: 1349215358000
java.lang.NullPointerException
    at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:78)
    at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:205)
    at com.android.internal.widget.ActionBarView$3.onClick(ActionBarView.java:167)
    at android.view.View.performClick(View.java:4084)
    at android.view.View.onKeyUp(View.java:7669)
    at android.view.KeyEvent.dispatch(KeyEvent.java:2633)
    at android.view.View.dispatchKeyEvent(View.java:7086)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1354)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1358)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1892)
    at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1369)
    at android.app.Activity.dispatchKeyEvent(Activity.java:2356)
    at com.actionbarsherlock.app.SherlockFragmentActivity.dispatchKeyEvent(SherlockFragmentActivity.java:122)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1819)
    at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3577)
    at android.view.ViewRootImpl.deliverKeyEvent(ViewRootImpl.java:3533)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3115)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4155)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4134)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4226)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:125)
    at android.os.Looper.loop(Looper.java:124)
    at android.app.ActivityThread.main(ActivityThread.java:4745)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by ghost** [comment]
I had the same problem here. I'm not doing much in my app related to ABS yet so I think it is probably a real bug.

**Comment by iNoles** [comment]
it looks like mMenu or item is null

**Comment by orrc** [comment]
I'm seeing this too in my app, also on the Galaxy Nexus with 4.1.2.

**Comment by orrc** [comment]
I added logging to `ActionBarSherlockNative#dispatchOptionsItemSelected(MenuItem)` to see what was happening (and added `return false` before the NPE would happen).

In every case, monkey crashes when clicking on the menu item `android.R.id.home` &mdash; i.e. the home button/icon.

Monkey somehow manages to click on a menu item before `onCreateOptionsMenu` has been called in an activity:

```
35.481 ABSherlock: Using implementation: ActionBarSherlockNative
35.481 ABSherlock: [<ctor>] activity: com.example.FooActivity@441f64f0, flags: 1
35.481 ABSherlock: [getActionBar]
35.504 ABSherlock: [setContentView] layoutResId: 2130903075
35.512 ABSherlock: [getActionBar]
36.582 ABSherlock: [dispatchOptionsItemSelected] item: null
36.582 System.out: >>>>>>>> menu fail on item ID '0x102002c', title 'Search'
36.582 ABSherlock: [dispatchOptionsItemSelected] item: null
36.582 System.out: >>>>>>>> menu fail on item ID '0x102002c', title 'Search'
36.590 ABSherlock: [dispatchCreateOptionsMenu] menu: com.android.internal.view.menu.MenuBuilder@420f2690
36.590 ABSherlock: [callbackCreateOptionsMenu] menu: com.actionbarsherlock.internal.view.menu.MenuWrapper@439e1590
36.590 ABSherlock: [getMenuInflater]
36.590 ABSherlock: [getActionBar]
36.590 ABSherlock: [getMenuInflater]
36.598 ABSherlock: [callbackCreateOptionsMenu] returning true
36.598 ABSherlock: [dispatchCreateOptionsMenu] returning true
36.598 ABSherlock: [dispatchPrepareOptionsMenu] menu: com.android.internal.view.menu.MenuBuilder@420f2690
```

Adding a `mMenu == null` check to `dispatchOptionsItemSelected` makes the monkey happy, and lets me test my app. :+1:

**Comment by JakeWharton** [comment]
Thanks for the detailed investigation! Blindly adding an `mMenu == null` check is the wrong solution but adding an `mMenu == null` check with an exact cause is correct.

**Comment by tkhduracell** [comment]
Thanks!

``` java
final boolean result = ( mMenu == null ? false : callbackOptionsItemSelected(mMenu.findItem(item)));
```

**Comment by kkocel** [comment]
@JakeWharton So what is exact fix for that issue? I can see no fix for it in master or in dev branch....
Beside the fact that it not only occurs on monkey but also in the wild.

**Comment by matthewmichihara** [comment]
I'm curious why you closed https://github.com/JakeWharton/ActionBarSherlock/pull/803 but not this? It seems like they are the same bug, but the fix (https://github.com/JakeWharton/ActionBarSherlock/commit/e9180ef9ea727e4bc0afbce682f80890ca40cd28) looks like it's still just a null check.

**Comment by JakeWharton** [comment]
I need to look at it again. I forgot this issue existed.

**Comment by blundell** [comment]
@JakeWharton What version of ABS is this fixed in? Is there an easy way to work that out for myself, so I don't have to ask next time?

**Comment by JakeWharton** [comment]
It's fixed on `dev`. Not released.

**Comment by blundell** [comment]
Any idea on a release timeframe? We have MonkeyRunner as part of our CI and it's exploding each night
