### ISSUE TITLE
Motorola phone has Resources$NotFoundException issues

### ISSUE THREAD

**Issue by Nyceane** [JakeWharton/ActionBarSherlock#703]
I've been keep getting this error on my bug report, apparently this only happens on Motorola phones.  I tested it through Droid 3 and Droid X but can't seem to replicate it but the crash report is keep having this poping up.

Also, all the report comes from 2.3.4, 2.3.5 and 2.3.6

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.Myapp/com.test.Myapp.v2.Activities.AddFoodActivity}: android.view.InflateException: Binary XML file line #3: Error inflating class <unknown>
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1696)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1716)
    at android.app.ActivityThread.access$1500(ActivityThread.java:124)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:968)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3806)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #3: Error inflating class <unknown>
    at android.view.LayoutInflater.createView(LayoutInflater.java:518)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
    at com.actionbarsherlock.internal.widget.ScrollingTabContainerView.createTabView(ScrollingTabContainerView.java:276)
    at com.actionbarsherlock.internal.widget.ScrollingTabContainerView.addTab(ScrollingTabContainerView.java:295)
    at com.actionbarsherlock.internal.app.ActionBarImpl.addTab(ActionBarImpl.java:449)
    at com.actionbarsherlock.internal.app.ActionBarImpl.addTab(ActionBarImpl.java:438)
    at com.test.Myapp.v2.Activities.AddFoodActivity.onCreate(AddFoodActivity.java:78)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1660)
    ... 11 more
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.constructNative(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
    at android.view.LayoutInflater.createView(LayoutInflater.java:505)
    ... 22 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abs__tab_indicator_ab_holo.xml from drawable resource ID #0x7f02005e
    at android.content.res.Resources.loadDrawable(Resources.java:1735)
    at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
    at android.view.View.<init>(View.java:1951)
    at android.view.View.<init>(View.java:1899)
    at android.view.ViewGroup.<init>(ViewGroup.java:286)
    at android.widget.LinearLayout.<init>(LinearLayout.java:120)
    at com.actionbarsherlock.internal.widget.ScrollingTabContainerView$TabView.<init>(ScrollingTabContainerView.java:373)
    ... 25 more
Caused by: java.lang.NullPointerException
    at android.graphics.drawable.DrawableContainer$DrawableContainerState.addChild(DrawableContainer.java:349)
    at android.graphics.drawable.StateListDrawable$StateListState.addStateSet(StateListDrawable.java:267)
    at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:175)
    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:795)
    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:736)
    at android.content.res.Resources.loadDrawable(Resources.java:1732)
    ... 31 more

**Comment by JakeWharton** [comment]
Moto probably broke resource loading. Probably nothing that can be fixed by the library.
