### ISSUE TITLE
VerifyError?

### ISSUE THREAD

**Issue by crossle** [JakeWharton/ActionBarSherlock#710]
``` java
java.lang.VerifyError: a
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.c(SourceFile:983)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(SourceFile:853)
    at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SourceFile:251)
    at ****.onCreate(SourceFile:68)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1050)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1782)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1834)
    at android.app.ActivityThread.access$500(ActivityThread.java:122)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1027)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:132)
    at android.app.ActivityThread.main(ActivityThread.java:4126)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:491)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
    at dalvik.system.NativeStart.main(Native Method)

```

**Comment by JakeWharton** [comment]
Needs more info. Device? API level? Maybe deobfuscate the stacktrace?
