### ISSUE TITLE
NoSuchFieldError in java.util.Locale.ROOT in CapitalizingButton.java

### ISSUE THREAD

**Issue by tarkeshwar** [JakeWharton/ActionBarSherlock#712]
https://github.com/JakeWharton/ActionBarSherlock/commit/f7808218998d85db971c781c7bb20a1427d8125c fixes same exception in CapitalizingTextView.java. Need similar check in CapitalizingButton.java too.

This is the exception I am getting:
"java.lang.NoSuchFieldError: java.util.Locale.ROOT
    at com.actionbarsherlock.internal.widget.CapitalizingButton.setTextCompat(CapitalizingButton.java:32)
    at com.actionbarsherlock.internal.view.menu.ActionMenuItemView.setTitle(ActionMenuItemView.java:204)
    at com.actionbarsherlock.internal.view.menu.ActionMenuItemView.initialize(ActionMenuItemView.java:129)
    at com.actionbarsherlock.internal.view.menu.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:192)
    at com.actionbarsherlock.internal.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:176)
    at com.actionbarsherlock.internal.view.menu.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:178)
    at com.actionbarsherlock.internal.view.menu.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:451)
    at com.actionbarsherlock.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1048)
    at com.actionbarsherlock.internal.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:89)
    at com.actionbarsherlock.internal.view.menu.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:206)
    at com.actionbarsherlock.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:247)
    at com.actionbarsherlock.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:946)
    at com.actionbarsherlock.internal.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:969)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:520)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:272)
    at com.actionbarsherlock.app.SherlockActivity.invalidateOptionsMenu(SherlockActivity.java:140)
    at com.actionbarsherlock.app.SherlockActivity.supportInvalidateOptionsMenu(SherlockActivity.java:144)
    at com.chatimity.android.chatimity.MenuManager$3.run(MenuManager.java:149)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:4627)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Merged to `dev`.
