### ISSUE TITLE
java.lang.IllegalStateException: ActionBarView can only be used with android:layout_height="wrap_content"

### ISSUE THREAD

**Issue by jlmalone** [JakeWharton/ActionBarSherlock#762]
This seems to happen only on the LG-C729

Version: 1413201
Android: 2.3.4
Manufacturer: LGE
Model: LG-C729
Date: Wed Dec 26 11:18:36 EST 2012

java.lang.IllegalStateException: ActionBarView can only be used with android:layout_height="wrap_content"
    at com.actionbarsherlock.internal.widget.ActionBarView.onMeasure(PofSourceFile:903)
    at android.view.View.measure(View.java:8446)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3180)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
    at com.actionbarsherlock.internal.widget.ActionBarContainer.onMeasure(PofSourceFile:188)
    at android.view.View.measure(View.java:8446)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3180)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1017)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:386)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:309)
    at android.view.View.measure(View.java:8446)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3180)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
    at android.view.View.measure(View.java:8446)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3180)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
    at android.view.View.measure(View.java:8446)
    at android.view.ViewRoot.performTraversals(ViewRoot.java:1077)
    at android.view.ViewRoot.handleMessage(ViewRoot.java:2373)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3740)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:876)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
This is probably an OEM's custom ROM with a broken resource loader. Or you're not using a theme from the library properly (but probably not).
