### ISSUE TITLE
NPE when calling setContentView multiple times

### ISSUE THREAD

**Issue by yannooo** [JakeWharton/ActionBarSherlock#769]
I receive crash reports from ACRA when calling setContentView multiple times on a SherlockFragmentActivity. Any clues on how to prevent it?

I'm using ActionBarShelock 4.2

```
java.lang.NullPointerException
        at android.view.ViewGroup.addFocusables(ViewGroup.java:876)
        at android.view.ViewGroup.addFocusables(ViewGroup.java:877)
        at android.view.ViewGroup.addFocusables(ViewGroup.java:877)
        at android.view.View.addFocusables(View.java:6368)
        at android.view.FocusFinder.findNextFocus(FocusFinder.java:92)
        at android.view.FocusFinder.findNextFocus(FocusFinder.java:65)
        at android.view.ViewRootImpl.focusSearch(ViewRootImpl.java:4036)
        at android.view.ViewRootImpl.clearChildFocus(ViewRootImpl.java:2575)
        at android.view.ViewGroup.clearChildFocus(ViewGroup.java:753)
        at android.view.ViewGroup.clearChildFocus(ViewGroup.java:753)
        at android.view.ViewGroup.clearChildFocus(ViewGroup.java:753)
        at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:3800)
        at android.view.ViewGroup.removeAllViews(ViewGroup.java:3732)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:268)
        at com.actionbarsherlock.internal.ActionBarSherlockNative.setContentView(ActionBarSherlockNative.java:119)
        at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:262)
....
```

**Comment by SimonVT** [comment]
When using the native action bar, ABS simply proxies setContentView to the framework. You should report this on http://b.android.com, or just stop calling setContentView multiple times.
