### ISSUE TITLE
Problem building with maven

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#816]
Hi,

I am trying to build my project with maven (using command line, no IDE). It requires r11 of the compatibility-v4 library. I have added an exclusion in the ABS dependency, but still I am always getting an error and I see that the r7 jar is being included.

My dependencies are (I am using the maven sdk deployer):

<dependencies>
        <dependency>
            <groupId>android</groupId>
            <artifactId>android</artifactId>
            <version>${android.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>android.support</groupId>
            <artifactId>compatibility-v4</artifactId>
            <version>11</version>
        </dependency>
        <dependency>
            <groupId>com.actionbarsherlock</groupId>
            <artifactId>actionbarsherlock</artifactId>
            <version>4.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.android</groupId>
                    <artifactId>support-v4</artifactId>
                </exclusion>
            </exclusions>
            <type>apklib</type>
        </dependency>
        <dependency>
            <groupId>com.google.android.admob</groupId>
            <artifactId>admob</artifactId>
            <version>6.2.1-r8</version>
        </dependency>
        <dependency>
            <groupId>com.google.android.gms</groupId>
            <artifactId>google-play-services</artifactId>
            <version>4</version>
            <type>apklib</type>
        </dependency>
        <dependency>
            <groupId>com.nostra13.universalimageloader</groupId>
            <artifactId>universal-image-loader</artifactId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
            <groupId>ch.acra</groupId>
            <artifactId>acra</artifactId>
            <version>4.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-io</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.7</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>r09</version>
        </dependency>
        <dependency>
            <groupId>net.sqlcipher</groupId>
            <artifactId>sqlcipher</artifactId>
            <version>2.1.1</version>
        </dependency>
        <dependency>
            <groupId>net.sqlcipher</groupId>
            <artifactId>libdatabase_sqlcipher</artifactId>
            <version>2.1.1</version>
            <type>so</type>
        </dependency>
        <dependency>
            <groupId>net.sqlcipher</groupId>
            <artifactId>libsqlcipher_android</artifactId>
            <version>2.1.1</version>
            <type>so</type>
        </dependency>
        <dependency>
            <groupId>net.sqlcipher</groupId>
            <artifactId>libstlport_shared</artifactId>
            <version>2.1.1</version>
            <type>so</type>
        </dependency>
        <dependency>
            <groupId>it.sephiroth.android</groupId>
            <artifactId>imagezoom</artifactId>
            <version>1.0.0</version>
            <type>apklib</type>
        </dependency>
        <dependency>
            <groupId>com.myproject</groupId>
            <artifactId>logging</artifactId>
            <type>apklib</type>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
</dependencies>

And the error I get is

[INFO] /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java [-Xmx1024M, -jar, /usr/local/Cellar/android-sdk/r20.0.3/platform-tools/lib/dx.jar, --dex, --output=/Users/admin/Documents/Android/workspace/MyProject/target/classes.dex, /Users/admin/.m2/repository/com/actionbarsherlock/actionbarsherlock/4.2.0/actionbarsherlock-4.2.0.apklib, /Users/admin/.m2/repository/com/google/android/support-v4/r7/support-v4-r7.jar, /Users/admin/.m2/repository/com/nostra13/universalimageloader/universal-image-loader/1.7.0/universal-image-loader-1.7.0.jar, /Users/admin/.m2/repository/com/google/android/gms/google-play-services/4/google-play-services-4.apklib, /Users/admin/.m2/repository/com/myproject/logging/1.0.0-SNAPSHOT/logging-1.0.0-SNAPSHOT.apklib, /Users/admin/.m2/repository/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.jar, /Users/admin/.m2/repository/it/sephiroth/android/imagezoom/1.0.0/imagezoom-1.0.0.apklib, /Users/admin/.m2/repository/net/sqlcipher/libstlport_shared/2.1.1/libstlport_shared-2.1.1.so, /Users/admin/.m2/repository/com/google/guava/guava/r09/guava-r09.jar, /Users/admin/.m2/repository/android/support/compatibility-v4/11/compatibility-v4-11.jar, /Users/admin/.m2/repository/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar, /Users/admin/.m2/repository/com/google/android/gms/google-play-services/4/google-play-services-4.jar, /Users/admin/Documents/Android/workspace/MyProject/target/classes, /Users/admin/.m2/repository/com/google/android/admob/admob/6.2.1-r8/admob-6.2.1-r8.jar, /Users/admin/.m2/repository/ch/acra/acra/4.4.0/acra-4.4.0.jar, /Users/admin/.m2/repository/net/sqlcipher/libdatabase_sqlcipher/2.1.1/libdatabase_sqlcipher-2.1.1.so, /Users/admin/.m2/repository/net/sqlcipher/sqlcipher/2.1.1/sqlcipher-2.1.1.jar, /Users/admin/.m2/repository/net/sqlcipher/libsqlcipher_android/2.1.1/libsqlcipher_android-2.1.1.so, /Users/admin/.m2/repository/commons-codec/commons-codec/1.7/commons-codec-1.7.jar, /Users/admin/.m2/repository/com/viewpagerindicator/library/2.4.1/library-2.4.1.apklib]
[INFO] 
[INFO] UNEXPECTED TOP-LEVEL EXCEPTION:
[INFO] java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/LoaderManager;
[INFO]  at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:123)
[INFO]  at com.android.dx.dex.file.DexFile.add(DexFile.java:163)
[INFO]  at com.android.dx.command.dexer.Main.processClass(Main.java:490)
[INFO]  at com.android.dx.command.dexer.Main.processFileBytes(Main.java:459)
[INFO]  at com.android.dx.command.dexer.Main.access$400(Main.java:67)
[INFO]  at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:398)
[INFO]  at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:245)
[INFO]  at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:131)
[INFO]  at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:109)
[INFO]  at com.android.dx.command.dexer.Main.processOne(Main.java:422)
[INFO]  at com.android.dx.command.dexer.Main.processAllFiles(Main.java:333)
[INFO]  at com.android.dx.command.dexer.Main.run(Main.java:209)
[INFO]  at com.android.dx.command.dexer.Main.main(Main.java:174)
[INFO]  at com.android.dx.command.Main.main(Main.java:91)

What can I do to solvde this problem?

Thanks

M.

**Comment by ghost** [comment]
Oh forget my issue, I had to add the exclusion also for com.viewpagerindicator.
