### ISSUE TITLE
view inflateException

### ISSUE THREAD

**Issue by codetalks-new** [JakeWharton/ActionBarSherlock#840]
from a android 2.3.5 system
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xiyili.youjia/com.xiyili.youjia.ui.PickSchoolv2Activity}: android.view.InflateException: Binary XML file line #24: Error inflating class <unknown>
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1686)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1702)
    at android.app.ActivityThread.access$1600(ActivityThread.java:118)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:952)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3768)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class <unknown>
    at android.view.LayoutInflater.createView(LayoutInflater.java:518)
    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
    at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2351)
    at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2406)
    at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1531)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.void installDecor()(Unknown Source)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.void setContentView(int)(Unknown Source)
                                                           void setContentView(android.view.View,android.view.ViewGroup$LayoutParams)
    at com.actionbarsherlock.app.SherlockFragmentActivity.void setContentView(int)(Unknown Source)
                                                       void setContentView(android.view.View,android.view.ViewGroup$LayoutParams)
                                                       void setContentView(android.view.View)
    at com.xiyili.youjia.ui.PickSchoolv2Activity.void onCreate(android.os.Bundle)(Unknown Source)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1046)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1650)
    ... 11 more
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.constructNative(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
    at android.view.LayoutInflater.createView(LayoutInflater.java:505)
    ... 25 more
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
    at android.view.View.<init>(View.java:2096)
    at android.view.ViewGroup.<init>(ViewGroup.java:294)
    at android.widget.FrameLayout.<init>(FrameLayout.java:88)
    at android.widget.FrameLayout.<init>(FrameLayout.java:84)
    ... 28 more
android.view.InflateException: Binary XML file line #24: Error inflating class <unknown>
    at android.view.LayoutInflater.createView(LayoutInflater.java:518)
    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
    at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2351)
    at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2406)
    at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1531)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.void installDecor()(Unknown Source)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.void setContentView(int)(Unknown Source)
                                                           void setContentView(android.view.View,android.view.ViewGroup$LayoutParams)
    at com.actionbarsherlock.app.SherlockFragmentActivity.void setContentView(int)(Unknown Source)
                                                       void setContentView(android.view.View,android.view.ViewGroup$LayoutParams)
                                                       void setContentView(android.view.View)
    at com.xiyili.youjia.ui.PickSchoolv2Activity.void onCreate(android.os.Bundle)(Unknown Source)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1046)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1650)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1702)
    at android.app.ActivityThread.access$1600(ActivityThread.java:118)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:952)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3768)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.constructNative(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
    at android.view.LayoutInflater.createView(LayoutInflater.java:505)
    ... 25 more
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
    at android.view.View.<init>(View.java:2096)
    at android.view.ViewGroup.<init>(ViewGroup.java:294)
    at android.widget.FrameLayout.<init>(FrameLayout.java:88)
    at android.widget.FrameLayout.<init>(FrameLayout.java:84)
    ... 28 more
java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.constructNative(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
    at android.view.LayoutInflater.createView(LayoutInflater.java:505)
    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
    at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2351)
    at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2406)
    at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1531)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.void installDecor()(Unknown Source)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.void setContentView(int)(Unknown Source)
                                                           void setContentView(android.view.View,android.view.ViewGroup$LayoutParams)
    at com.actionbarsherlock.app.SherlockFragmentActivity.void setContentView(int)(Unknown Source)
                                                       void setContentView(android.view.View,android.view.ViewGroup$LayoutParams)
                                                       void setContentView(android.view.View)
    at com.xiyili.youjia.ui.PickSchoolv2Activity.void onCreate(android.os.Bundle)(Unknown Source)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1046)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1650)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1702)
    at android.app.ActivityThread.access$1600(ActivityThread.java:118)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:952)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3768)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
    at android.view.View.<init>(View.java:2096)
    at android.view.ViewGroup.<init>(ViewGroup.java:294)
    at android.widget.FrameLayout.<init>(FrameLayout.java:88)
    at android.widget.FrameLayout.<init>(FrameLayout.java:84)
    ... 28 more
java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
    at android.view.View.<init>(View.java:2096)
    at android.view.ViewGroup.<init>(ViewGroup.java:294)
    at android.widget.FrameLayout.<init>(FrameLayout.java:88)
    at android.widget.FrameLayout.<init>(FrameLayout.java:84)
    at java.lang.reflect.Constructor.constructNative(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
    at android.view.LayoutInflater.createView(LayoutInflater.java:505)
    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
    at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2351)
    at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2406)
    at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1531)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.void installDecor()(Unknown Source)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.void setContentView(int)(Unknown Source)
                                                           void setContentView(android.view.View,android.view.ViewGroup$LayoutParams)
    at com.actionbarsherlock.app.SherlockFragmentActivity.void setContentView(int)(Unknown Source)
                                                       void setContentView(android.view.View,android.view.ViewGroup$LayoutParams)
                                                       void setContentView(android.view.View)
    at com.xiyili.youjia.ui.PickSchoolv2Activity.void onCreate(android.os.Bundle)(Unknown Source)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1046)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1650)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1702)
    at android.app.ActivityThread.access$1600(ActivityThread.java:118)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:952)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3768)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Need more info on the phone. Probably some custom OEM ROM that we can't really fix.

**Comment by codetalks-new** [comment]
well,sorry for cant give more info,it's a chinese MEIZU M9 smartcellphone.
en,can you give me some tip to find the bug? Thank you.

**Comment by iNoles** [comment]
Do You use any Custom Theme?

**Comment by JakeWharton** [comment]
Dupe #446.
