### ISSUE TITLE
java.lang.OutOfMemoryError: bitmap size exceeds VM budget

### ISSUE THREAD

**Issue by alexzaitsev** [JakeWharton/ActionBarSherlock#852]
My ACRA reports notified me about this strange crash:

java.lang.RuntimeException: Unable to start activity ComponentInfo{net.aviascanner.aviascanner/net.aviascanner.aviascanner.ui.activities.SearchResultsActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1659)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:2853)
        at android.app.ActivityThread.access$1600(ActivityThread.java:121)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:947)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3701)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:518)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
        at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:853)
        at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:262)
        at net.aviascanner.aviascanner.ui.activities.SearchResultsActivity.onCreate(SearchResultsActivity.java:104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
        ... 12 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
        at android.view.LayoutInflater.createView(LayoutInflater.java:505)
        ... 22 more
Caused by: java.lang.OutOfMemoryError: bitmap size exceeds VM budget
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:477)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:444)
        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:349)
        at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:532)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:507)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:370)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:715)
        at android.content.res.Resources.loadDrawable(Resources.java:1720)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
        at android.view.View.<init>(View.java:1975)
        at android.view.View.<init>(View.java:1923)
        at android.view.ViewGroup.<init>(ViewGroup.java:314)
        at android.widget.LinearLayout.<init>(LinearLayout.java:124)
        ... 25 more
android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:518)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
        at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:853)
        at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:262)
        at net.aviascanner.aviascanner.ui.activities.SearchResultsActivity.onCreate(SearchResultsActivity.java:104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:2853)
        at android.app.ActivityThread.access$1600(ActivityThread.java:121)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:947)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3701)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
        at android.view.LayoutInflater.createView(LayoutInflater.java:505)
        ... 22 more
Caused by: java.lang.OutOfMemoryError: bitmap size exceeds VM budget
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:477)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:444)
        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:349)
        at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:532)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:507)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:370)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:715)
        at android.content.res.Resources.loadDrawable(Resources.java:1720)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
        at android.view.View.<init>(View.java:1975)
        at android.view.View.<init>(View.java:1923)
        at android.view.ViewGroup.<init>(ViewGroup.java:314)
        at android.widget.LinearLayout.<init>(LinearLayout.java:124)
        ... 25 more
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
        at android.view.LayoutInflater.createView(LayoutInflater.java:505)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
        at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:853)
        at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:262)
        at net.aviascanner.aviascanner.ui.activities.SearchResultsActivity.onCreate(SearchResultsActivity.java:104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:2853)
        at android.app.ActivityThread.access$1600(ActivityThread.java:121)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:947)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3701)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.OutOfMemoryError: bitmap size exceeds VM budget
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:477)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:444)
        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:349)
        at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:532)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:507)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:370)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:715)
        at android.content.res.Resources.loadDrawable(Resources.java:1720)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
        at android.view.View.<init>(View.java:1975)
        at android.view.View.<init>(View.java:1923)
        at android.view.ViewGroup.<init>(ViewGroup.java:314)
        at android.widget.LinearLayout.<init>(LinearLayout.java:124)
        ... 25 more
java.lang.OutOfMemoryError: bitmap size exceeds VM budget
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:477)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:444)
        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:349)
        at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:532)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:507)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:370)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:715)
        at android.content.res.Resources.loadDrawable(Resources.java:1720)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
        at android.view.View.<init>(View.java:1975)
        at android.view.View.<init>(View.java:1923)
        at android.view.ViewGroup.<init>(ViewGroup.java:314)
        at android.widget.LinearLayout.<init>(LinearLayout.java:124)
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
        at android.view.LayoutInflater.createView(LayoutInflater.java:505)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
        at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:853)
        at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:262)
        at net.aviascanner.aviascanner.ui.activities.SearchResultsActivity.onCreate(SearchResultsActivity.java:104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:2853)
        at android.app.ActivityThread.access$1600(ActivityThread.java:121)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:947)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3701)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
This is your layout that you pass to `setContentView` [being inflated into ABS' container](https://github.com/JakeWharton/ActionBarSherlock/blob/4.2.0/library/src/com/actionbarsherlock/internal/ActionBarSherlockCompat.java#L853). Not an ABS bug.
