### ISSUE TITLE
Samsung Tab2 - Cannot interact with object designed for temporary instance passing. Make sure you using both SherlockFragmentActivity and SherlockFragment.

### ISSUE THREAD

**Issue by sameersegal** [JakeWharton/ActionBarSherlock#865]
Hi, I looked at issue #440 - I am using ABS 4.2 and get this issue on Samsung Tab2. I initially thought this was because of SlidingMenu but I commented the line out (for toggling SlidingMenu) and the error remains. (The SlidingMenu demo crashes on Tab2).

I have tested this code on:
- Nexus S - 4.0.2 -- works well
- Tab2 - 4.1.2 (tablet) -- crashes.

Am I missing something for tablets or is this a bug in Tab2?

```
@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
        case android.R.id.home:
            //getSlidingMenu().toggle();
            return false;
        default:
            return false;
        }
    }
```

```
E/AndroidRuntime(26918): java.lang.IllegalStateException: Cannot interact with object designed for temporary instance passing. Make sure you using both SherlockFragmentActivity and SherlockFragment.
E/AndroidRuntime(26918):    at com.actionbarsherlock.internal.view.menu.MenuItemMule.getItemId(MenuItemMule.java:71)
E/AndroidRuntime(26918):    at android.app.Activity.onMenuItemSelected(Activity.java:2612)
E/AndroidRuntime(26918):    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
E/AndroidRuntime(26918):    at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:283)
E/AndroidRuntime(26918):    at com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:587)
E/AndroidRuntime(26918):    at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:78)
E/AndroidRuntime(26918):    at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:193)
E/AndroidRuntime(26918):    at com.android.internal.widget.ActionBarView$3.onClick(ActionBarView.java:179)
E/AndroidRuntime(26918):    at android.view.View.performClick(View.java:4222)
E/AndroidRuntime(26918):    at android.view.View$PerformClick.run(View.java:17337)
E/AndroidRuntime(26918):    at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime(26918):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(26918):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(26918):    at android.app.ActivityThread.main(ActivityThread.java:4895)
E/AndroidRuntime(26918):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(26918):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(26918):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
E/AndroidRuntime(26918):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
E/AndroidRuntime(26918):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by iNoles** [comment]
Update your ABS!!! MenuMule is nolonger needed.

**Comment by sameersegal** [comment]
I am on the master branch -- `[maven-release-plugin] prepare release 4.2.0`. What version should I be using?

**Comment by iNoles** [comment]
http://search.maven.org/#artifactdetails|com.actionbarsherlock|library|4.2.0|pom 4.2.0

**Comment by sameersegal** [comment]
Sorry about this. I thought I was running 4.2, I did a `git checkout / reset` and its working. Thanks for the help
