### ISSUE TITLE
NullPointerException in SherlockFragmentActivity.java onDestroy()...

### ISSUE THREAD

**Issue by tucson-tom** [JakeWharton/ActionBarSherlock#886]
Just updated to the latest SlidingMenu and v4 Android support library.  ActionBarSherlock version remains at 4.2.0 (latest).  Now ActionBarSherlock crashes occasionally when calling onDestroy()...

```
04-02 11:55:28.485: E/AndroidRuntime(14719): java.lang.RuntimeException: Unable to destroy activity {com.....MyActivity}: java.lang.NullPointerException
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3315)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3333)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.app.ActivityThread.access$1300(ActivityThread.java:139)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.os.Handler.dispatchMessage(Handler.java:99)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.os.Looper.loop(Looper.java:137)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.app.ActivityThread.main(ActivityThread.java:4918)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at java.lang.reflect.Method.invokeNative(Native Method)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at java.lang.reflect.Method.invoke(Method.java:511)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at dalvik.system.NativeStart.main(Native Method)
04-02 11:55:28.485: E/AndroidRuntime(14719): Caused by: java.lang.NullPointerException
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.webkit.WebViewClassic.requestFocus(WebViewClassic.java:10231)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.webkit.WebView.requestFocus(WebView.java:2133)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2341)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2341)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.View.requestFocus(View.java:6538)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.View.requestFocus(View.java:6517)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.View.ensureInputFocusOnFirstFocusable(View.java:4471)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3675)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3635)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.removeView(ViewGroup.java:3567)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.support.v4.view.ViewPager.removeView(ViewPager.java:1259)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1009)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1070)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1898)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:324)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at com.actionbarsherlock.app.SherlockFragmentActivity.onDestroy(SherlockFragmentActivity.java:88)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.app.Activity.performDestroy(Activity.java:5212)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1124)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3302)
04-02 11:55:28.485: E/AndroidRuntime(14719):    ... 11 more
```

The activity layout is a ListView that starts a viewing activity when the list item is clicked.  The crash happens at the exact same spot in ActionBarSherlock (the line is super.onDestroy()).  The quick hacky fix is to change SherlockFragmentActivity.java onDestroy() to:

```
    @Override
    protected void onDestroy() {
        getSherlock().dispatchDestroy();
        try {
            super.onDestroy();
        } catch (Exception $e) {
        }
    }
```

Maybe look into this a bit?  Obviously, burying exceptions is not the best solution.  I'm actually importing the v13 support library instead of the v4 support library, if that makes a difference.

**Comment by JakeWharton** [comment]
If you want to catch exceptions, do it in your activity's call to `super.onDispatch()`.

Your real problem is here, which has nothing to do with ABS:

```
04-02 11:55:28.485: E/AndroidRuntime(14719): Caused by: java.lang.NullPointerException
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.webkit.WebViewClassic.requestFocus(WebViewClassic.java:10231)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.webkit.WebView.requestFocus(WebView.java:2133)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2341)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2338)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2382)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.requestFocus(ViewGroup.java:2341)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.View.requestFocus(View.java:6538)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.View.requestFocus(View.java:6517)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.View.ensureInputFocusOnFirstFocusable(View.java:4471)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3675)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3635)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.view.ViewGroup.removeView(ViewGroup.java:3567)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.support.v4.view.ViewPager.removeView(ViewPager.java:1259)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1009)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1070)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1898)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:324)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at com.actionbarsherlock.app.SherlockFragmentActivity.onDestroy(SherlockFragmentActivity.java:88)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.app.Activity.performDestroy(Activity.java:5212)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1124)
04-02 11:55:28.485: E/AndroidRuntime(14719):    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3302)
```

**Comment by tucson-tom** [comment]
Figured it out.  It had to do with a detached WebView not being cleaned up properly.  The problem manifested itself as a crash in ABS.  Sorry to bother you.

**Comment by pepitoria** [comment]
Hi,

I am having this issue too. I have the problem with a fragment I use to insert ads from admob. 

@tucson-tom how did you make to fix this?

In my case is due to this piece of code in onDestroy of the fragment:

if (adView != null) {
   adView.destroy();
}

If I remove it, it stops crashing. Admob uses a webview internally so I wonder how did you managed to clean it up.

**Comment by tucson-tom** [comment]
My problem wasn't onDestroy() (I ran into a crash bug with code similar to yours as well).  I was replacing the current ad with a new one.  It ended up being fairly simple:

```
if (adView != null)
{
  RelativeLayout rl = (RelativeLayout)findViewById(R.id.ad_wrapper);

  rl.removeView(adView);
  adView.destroy();
}
```

I don't know how well findViewById() will work from within onDestroy().  In theory, it should automatically clean it up.

IMO, the documentation on AdMob and DFP is wrong and, for whatever reason, iOS is listed first, which implies that the Android stuff is being treated like a second-class citizen.

**Comment by pepitoria** [comment]
Looks like that solved my issue too. Thanks!

**Comment by 0xohzsh** [comment]
@tucson-tom 
It solved my issue too... Did you get into any trouble while using findViewById in ondestroy?

**Comment by tucson-tom** [comment]
@technohowl - Haven't seen any issues with it here but that doesn't mean anything.  Calling a UI function to find a UI element in a call like onDestroy() is just asking for trouble later on if the Android OS changes :)
