### ISSUE TITLE
java.lang.IllegalAccessError: tried to access field

### ISSUE THREAD

**Issue by neobie** [JakeWharton/ActionBarSherlock#907]
I have no issue during debugging my app in emulators or in my Nexus 4, ranging from API 8 to API 16.

However, there is a crash logs in Developer Console, and due to no message sent by user, I am unable to identify the Android Version as well as the Device they are using, to reproduce the error.

Here is the error logs:

java.lang.IllegalAccessError: tried to access field android.support.v4.app.Watson.mFragments from class android.support.v4.app.Watson
at android.support.v4.app.Watson.onCreatePanelMenu(Watson.java:51)
at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:559)
at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:479)
at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:272)
at com.actionbarsherlock.app.SherlockFragmentActivity.invalidateOptionsMenu(SherlockFragmentActivity.java:150)
at com.actionbarsherlock.app.SherlockFragmentActivity.supportInvalidateOptionsMenu(SherlockFragmentActivity.java:156)
at android.support.v4.app.Fragment.setHasOptionsMenu(Fragment.java:702)
at net.neobie.klse.MainMenuFragment.onCreateView(MainMenuFragment.java:45)

For more details , please refer to my post in stackoverflow.com
http://stackoverflow.com/questions/16127503/java-lang-illegalaccesserror-tried-to-access-field

Wish anyone can help me. Thanks!

**Comment by iNoles** [comment]
Why you have this.setHasOptionsMenu(true); in onCreateView? It should be onActivityCreated

**Comment by JakeWharton** [comment]
Hard to repro or debug without more info, sorry. Watson lives in the same package as FragmentManager so that it can spy on some package-private fields. This really can't cause problems because both the support library and ABS are in the same classloader.
