### ISSUE TITLE
mvn fail with robolectric 2.0-alpha-2, robolectric 2.0-alpha-1 is ok

### ISSUE THREAD

**Issue by tianyuanzhonglu** [JakeWharton/ActionBarSherlock#908]
windows 7 professional + maven 3.0.3 + actionbarsherlock 4.3.0.zip
d:> mvn clean package
prompts:
...
[INFO] Surefire report directory: D:\ActionBarSherlock\ActionBarSherlock\actionb
arsherlock\target\surefire-reports

---
##  T E S T S

Running com.actionbarsherlock.internal.ResourcesCompatTest
Warning: an error occurred while binding shadow class: ShadowGeoPoint
Warning: an error occurred while binding shadow class: ShadowItemizedOverlay
Warning: an error occurred while binding shadow class: ShadowMapController
Warning: an error occurred while binding shadow class: ShadowMapActivity
Warning: an error occurred while binding shadow class: ShadowMapView
Warning: an error occurred while binding shadow class: ShadowOverlayItem
java.lang.RuntimeException: Stub!
        at android.net.Uri.$$robo$$Uri_30fc_parse(Uri.java:53)
        at org.robolectric.bytecode.ShadowWrangler$InvocationPlan.callOriginal(S
hadowWrangler.java:591)
        at android.net.Uri.parse(Uri.java)
        at org.robolectric.shadows.ShadowMediaStore.reset(ShadowMediaStore.java:
27)
        at org.robolectric.Robolectric.resetStaticState(Robolectric.java:821)
        at org.robolectric.RobolectricTestRunner.resetStaticState(RobolectricTes
tRunner.java:224)
        at org.robolectric.RobolectricTestRunner.internalBeforeTest(RobolectricT
estRunner.java:133)
        at org.robolectric.RobolectricTestRunner.methodBlock(RobolectricTestRunn
er.java:96)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:68)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:47)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:124)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2
(ReflectionUtils.java:208)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke
(ProviderFactory.java:159)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(Provi
derFactory.java:87)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
95)
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.57 sec <<< FAI
LURE!
com.actionbarsherlock.internal.ResourcesCompatTest  Time elapsed: 7.57 sec  <<<
ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Stub!
        at android.net.Uri.$$robo$$Uri_30fc_parse(Uri.java:53)
        at org.robolectric.bytecode.ShadowWrangler$InvocationPlan.callOriginal(S
hadowWrangler.java:591)
        at android.net.Uri.parse(Uri.java)
        at org.robolectric.shadows.ShadowMediaStore.reset(ShadowMediaStore.java:
27)
        at org.robolectric.Robolectric.resetStaticState(Robolectric.java:821)
        at org.robolectric.RobolectricTestRunner.resetStaticState(RobolectricTes
tRunner.java:224)
        at org.robolectric.RobolectricTestRunner.internalBeforeTest(RobolectricT
estRunner.java:133)
        at org.robolectric.RobolectricTestRunner.methodBlock(RobolectricTestRunn
er.java:96)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:68)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:47)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:124)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2
(ReflectionUtils.java:208)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke
(ProviderFactory.java:159)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(Provi
derFactory.java:87)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
95)

Results :

Tests in error:
   ? Runtime java.lang.RuntimeException: Stub!

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] ActionBarSherlock (Parent) ........................ SUCCESS [0.270s]
[INFO] ActionBarSherlock ................................. FAILURE [14.210s]
[INFO] ActionBarSherlock FEST Assertions ................. SKIPPED
[INFO] ActionBarSherlock i18n ............................ SKIPPED
[INFO] Sample (Parent) ................................... SKIPPED
[INFO] Sample: Demos ..................................... SKIPPED
[INFO] Sample: Fragments ................................. SKIPPED
[INFO] Sample: Known Bugs ................................ SKIPPED
[INFO] Sample: RoboGuice ................................. SKIPPED
[INFO] Sample: Styled .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.440s
[INFO] Finished at: Tue Apr 23 01:06:15 CST 2013
[INFO] Final Memory: 14M/67M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
14.1:test (default-test) on project actionbarsherlock: There are test failures.
[ERROR]
[ERROR] Please refer to D:\ActionBarSherlock\ActionBarSherlock\actionbarsherlock
\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :actionbarsherlock

**Comment by JakeWharton** [comment]
There was a bug. Updated to 2.0 on `dev` @ 88f1ffff5ce9eed6f734ca9387c03abe7464a94c
