### ISSUE TITLE
java.lang.NumberFormatException: unable to parse '@2131558494' as integer

### ISSUE THREAD

**Issue by virsir** [JakeWharton/ActionBarSherlock#917]
i use 4.2.0, In some users' devices, 2.3.5, it crashed.

Caused by: java.lang.NumberFormatException: unable to parse '@2131558494' as integer
    at java.lang.Integer.parse(Integer.java:414)
    at java.lang.Integer.parseInt(Integer.java:403)
    at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:153)
    at android.content.res.TypedArray.getInt(TypedArray.java:286)
    at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2216)
    at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2358)
    at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1503)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.installDecor(SourceFile:898)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(SourceFile:849)
    at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SourceFile:262)
    at com.virsir.android.atrain.Navigator.onCreate(SourceFile:116)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1692)

**Comment by azwar** [comment]
@ character is not integer type, you can remove it if you want to parse to integer
