### ISSUE TITLE
setHasOptionsMenu behavior

### ISSUE THREAD

**Issue by martinpelant** [JakeWharton/ActionBarSherlock#935]
On older devices where AB is handled by ABS (Android 4.0.4) the menu is created right away when calling setHasOptionsMenu(true) from fragment's onCreate method causing possible NPE if the we rely on objects in onCreateOptionsMenu that are created later in onCreate.

On Android 4.2.2 the onCreateOptionsMenu is called AFTER fragment's onCreate.

**Comment by JakeWharton** [comment]
ABS does almost nothing on Android 4.0 and up.

**Comment by martinpelant** [comment]
I have this stackTrace from sony Xperia pro running 4.0.4
java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.eman.imes/cz.activity.TrafficActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1967)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992)
    at android.app.ActivityThread.access$600(ActivityThread.java:127)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4441)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at cz.fragment.traffic.ParkingListFragment.onCreateOptionsMenu(ParkingListFragment.java:189)
    at android.support.v4.app.Watson.onCreatePanelMenu(Watson.java:55)
    at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:559)
    at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchCreateOptionsMenu(ActionBarSherlockNative.java:65)
    at com.actionbarsherlock.app.SherlockFragmentActivity.onCreatePanelMenu(SherlockFragmentActivity.java:165)
    at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:407)
    at com.android.internal.policy.impl.PhoneWindow.invalidatePanelMenu(PhoneWindow.java:758)
    at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchInvalidateOptionsMenu(ActionBarSherlockNative.java:52)
    at com.actionbarsherlock.app.SherlockFragmentActivity.invalidateOptionsMenu(SherlockFragmentActivity.java:150)
    at com.actionbarsherlock.app.SherlockFragmentActivity.supportInvalidateOptionsMenu(SherlockFragmentActivity.java:156)
    at android.support.v4.app.Fragment.setHasOptionsMenu(Fragment.java:763)
    at cz.fragment.traffic.ParkingListFragment.onCreate(ParkingListFragment.java:104)
    at android.support.v4.app.Fragment.performCreate(Fragment.java:1437)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:877)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
    at cz.activity.base.BaseFragmentActivity.onStart(BaseFragmentActivity.java:161)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1133)
    at android.app.Activity.performStart(Activity.java:4475)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1940)
    ... 11 more

**Comment by JakeWharton** [comment]
You should call `setHasOptionsMenu` in `onActivityCreate` not `onCreate`.

**Comment by martinpelant** [comment]
Ok thx.
just of pure curiosity, is it officially documented somewhere that I shouldn't call it from onCreate?

**Comment by martinpelant** [comment]
Because on this page it says 

" In order for this method to receive calls, however, you must call setHasOptionsMenu() during onCreate(), to indicate that the fragment would like to add items to the Options Menu (otherwise, the fragment will not receive a call to onCreateOptionsMenu())."

http://developer.android.com/guide/components/fragments.html

**Comment by yincrash** [comment]
This caught me as well. I was calling `setHasOptionsMenu` in `onAttach`, and my `onCreateOptionsMenu` was being called after `onCreateView` in Android 4.2.2, but before it on my 4.0.4 device.

Moving to `onActivityCreated` seems to be acceptable since it ensures that it is consistently called after `onCreateView`

**Comment by JakeWharton** [comment]
Yeah there's something racy going on here. There are two other bugs tracking that raciness therefore I am closing this. Stick with what works, though.

**Comment by Frankiel** [comment]
fuck u
