### ISSUE TITLE
NPE in SherlockPreferenceActivity on 2.3

### ISSUE THREAD

**Issue by nelenkov** [JakeWharton/ActionBarSherlock#96]
This is from running the demo app on N1 (CM 2.3.7) and NS (stock 2.3.6):

``` java
E/AndroidRuntime(10221): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.actionbarsherlock.sample.demos/com.actionbarsherlock.sample.demos.app.ActionBarPreferenceActivity}: java.lang.NullPointerException
E/AndroidRuntime(10221):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1768)
E/AndroidRuntime(10221):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
E/AndroidRuntime(10221):    at android.app.ActivityThread.access$1500(ActivityThread.java:123)
E/AndroidRuntime(10221):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
E/AndroidRuntime(10221):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10221):    at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime(10221):    at android.app.ActivityThread.main(ActivityThread.java:3835)
E/AndroidRuntime(10221):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10221):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime(10221):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
E/AndroidRuntime(10221):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
E/AndroidRuntime(10221):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(10221): Caused by: java.lang.NullPointerException
E/AndroidRuntime(10221):    at android.support.v4.app.SherlockPreferenceActivity.ensureSupportActionBarAttached(SherlockPreferenceActivity.java:156)
E/AndroidRuntime(10221):    at android.support.v4.app.SherlockPreferenceActivity.onCreate(SherlockPreferenceActivity.java:262)
E/AndroidRuntime(10221):    at com.actionbarsherlock.sample.demos.app.ActionBarPreferenceActivity.onCreate(ActionBarPreferenceActivity.java:44)
E/AndroidRuntime(10221):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
E/AndroidRuntime(10221):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1722)
E/AndroidRuntime(10221):    ... 11 more
W/ActivityManager(  165):   Force finishing activity com.actionbarsherlock.sample.demos/.app.ActionBarPreferenceActivity
W/ActivityManager(  165):   Force finishing activity com.actionbarsherlock.sample.demos/.Support4Demos
```

**Comment by UweTrottmann** [comment]
Also happens in a 2.1 emulator. As the layouts in that line of code are properly defined it seems like getLayoutManager() is returning null for whatever reason...
Or the new non-final resource identifiers are to blame.

**Comment by iNoles** [comment]
I always wondering, why it need ListView to be added to that view?

**Comment by JakeWharton** [comment]
GItHub wasn't sending me email updates on new issues by default for some reason. Just noticed this and will investigate later today.

**Comment by JakeWharton** [comment]
Well I can't seem to reproduce this on either my phone or the emulator. The line in question is:

``` java
((ViewGroup)view.findViewById(R.id.abs__content)).addView(contentView);
```

which leads me to believe it's an `R.java` issue. Are you using the APK from the market/downloads or building yourself?

**Comment by UweTrottmann** [comment]
I guess nelenkov did run it on actual devices, I did compile myself (tested with the SeriesGuide source code).

edit: the demo apk works on my personal device (running a 2.3.7 ROM), it only crashes on config changes.

**Comment by nelenkov** [comment]
The demo app from the market works fine. If I build it myself, or try to integrate into my project, I get the NPE. It does seem that it only happens when I add the plugin as a jar though -- if I add the preferences project as a library project, it works fine. Wonder what the difference is...

**Comment by JakeWharton** [comment]
The whole point of the ADT 14 changes was to eliminate this problem. I
wonder if the maven compilation somehow inlined the values. I'll try
disassembling it when I get back to the hotel to see. For now you can set
it up as another library project which will fix the errors (that's how the
market app was compiled).

---

Jake Wharton
http://about.me/jakewharton
On Nov 2, 2011 9:27 PM, "Nikolay Elenkov" <
reply@reply.github.com>
wrote:

**Comment by nelenkov** [comment]
Thanks, will use the library project for now, seems to work fine. I'm using ADT15 FWIW. 

BTW, don't think this is related, but the package name in the manifest is 'com.actionbarsherlock.plugin.maps', and there are two R.java files in the library project.

**Comment by xDragonZ** [comment]
That's weird , why i cant find any android.support.v4.app.SherlockPreferenceActivity in the latest 3.4.0 release? 

Did you forget to include it or it only available in demo only?

**Comment by JakeWharton** [comment]
Its a plugin. Check http://abs.io/download

---

Jake Wharton
http://about.me/jakewharton
On Nov 2, 2011 10:12 PM, "xDragonZ" <
reply@reply.github.com>
wrote:

**Comment by xDragonZ** [comment]
Thanks, and i got NPE too... i spend few hours on this... :/ trying this method now https://github.com/JakeWharton/ActionBarSherlock/issues/96#issuecomment-2613159

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxxcom.xxx.xxx.ui.np}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1768)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
at android.app.ActivityThread.access$1500(ActivityThread.java:123)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3835)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at android.support.v4.app.SherlockPreferenceActivity.ensureSupportActionBarAttached(SherlockPreferenceActivity.java:156)
at android.support.v4.app.SherlockPreferenceActivity.onCreate(SherlockPreferenceActivity.java:262)
at com.xxx.xxx.ui.np.onCreate(np.java:22)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1722)
... 11 more
java.lang.NullPointerException
at android.support.v4.app.SherlockPreferenceActivity.ensureSupportActionBarAttached(SherlockPreferenceActivity.java:156)
at android.support.v4.app.SherlockPreferenceActivity.onCreate(SherlockPreferenceActivity.java:262)
at com.xxxpxxxl.ui.np.onCreate(np.java:22)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1722)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
at android.app.ActivityThread.access$1500(ActivityThread.java:123)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3835)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Both plugins seemed to have their `R.java` values inlined during compilation due to the use of Maven. The android plugin hasn't been updated to specifically account for ADT 14 and as a result the generated `R.java` file contains `static final int`s rather than just `static int`s.

I've posted to their mailing list and am waiting to hear back. For now, as said previously, use both plugins as additional library projects until I can get new plugins out there.
